### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by tc14077** [AmolGangadhare/flutter_barcode_scanner#103]
**Describe the bug**
After I updated the version of flutter_barcode_scanner package from ^0.1.7 to ^1.0.0, the application will crash when it finish the build.

**To Reproduce**
1. Update the package version in pubspec.yaml
2. Running debug build in vscode.

**Expected behavior**
1. The application will crash after the app-debug.apk is built. And the status will keep showing "installing build/app/outputs/apk/app.apk...".
2. An alert box is popped out and say the application keeps stopping if I tried to build my app couple of times.

**Smartphone (please complete the following information):**
 - Device: Nokia 7.2
 - OS: Android 10

**Flutter Doctor**
[✓] Flutter (Channel unknown, v1.12.13+hotfix.9, on Mac OS X 10.15.5 19F101, locale XXX)
    • Flutter version 1.12.13+hotfix.9 at ___
    • Framework revision f139b11009 (3 months ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at ___
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.37.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.1

[✓] VS Code (version 1.46.1)
    • VS Code at ___
    • Flutter extension version 3.12.1

[✓] Connected device (1 available)
    • Nokia 7 2 • N0AA002182K31700207 • android-arm64 • Android 10 (API 29)

• No issues found!

**Comment by msandwidi** [comment]
I have the same issue when upgrading from 0.7.0 to 1.0.0

**Comment by AmolGangadhare** [comment]
Can you do `flutter clean` and then try rebuilding again?

**Comment by tc14077** [comment]
> Can you do `flutter clean` and then try rebuilding again?

Sorry for my late response! There are few updates on this issue. After I followed the instructions [here](https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects), the project is able to finish the build with version ^1.0.0. 

**1. App crash after scanning**

However, my application will crash after the scanning of the qrcode or the cancel of the scanning. The error log is shown as follow:

```
D/Camera  (15363): app passed NULL surface
D/AndroidRuntime(15363): Shutting down VM
E/AndroidRuntime(15363): FATAL EXCEPTION: main
E/AndroidRuntime(15363): Process: com.my.app, PID: 15363
E/AndroidRuntime(15363): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=9001, result=0, data=Intent { (has extras) }} to activity {com.lambdasense.internal/com.lambdasense.internal.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.MethodChannel$Result.success(java.lang.Object)' on a null object reference
E/AndroidRuntime(15363): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4846)
E/AndroidRuntime(15363): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4887)
E/AndroidRuntime(15363): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
E/AndroidRuntime(15363): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime(15363): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime(15363): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2017)
E/AndroidRuntime(15363): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime(15363): 	at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime(15363): 	at android.app.ActivityThread.main(ActivityThread.java:7397)
E/AndroidRuntime(15363): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(15363): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/AndroidRuntime(15363): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
E/AndroidRuntime(15363): Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.MethodChannel$Result.success(java.lang.Object)' on a null object reference
E/AndroidRuntime(15363): 	at com.amolg.flutterbarcodescanner.FlutterBarcodeScannerPlugin.onActivityResult(FlutterBarcodeScannerPlugin.java:157)
E/AndroidRuntime(15363): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEnginePluginRegistry.java:634)
E/AndroidRuntime(15363): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry.onActivityResult(FlutterEnginePluginRegistry.java:367)
E/AndroidRuntime(15363): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:546)
E/AndroidRuntime(15363): 	at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:594)
E/AndroidRuntime(15363): 	at android.app.Activity.dispatchActivityResult(Activity.java:8301)
E/AndroidRuntime(15363): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4839)
E/AndroidRuntime(15363): 	... 11 more
I/Process (15363): Sending signal. PID: 15363 SIG: 9
Lost connection to device.
Exited (sigterm)

```

**2. If I kept the the application package at ^0.1.7 , it will crash when it finish the build.**
 I think it might related to the change that I had done according to instructions [here](https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects).

**Comment by tc14077** [comment]
I think I am encountering same issue #91?

**Comment by tc14077** [comment]
I tried to create a new sample project and directly teste the latest version of flutter_barcode_scanner package. The application is still crashing after the scanning is done. More precisely, the scanning is done and I can print out the Qrcode but the application just crash afterwards.

**Comment by jvlivz** [comment]
Same issue after upgrading from 0.1.7 to 1.0.1. 
Plataform Android.

**Comment by dabodamjan** [comment]
same issue for me

**Comment by metalinspired** [comment]
same
