### ISSUE TITLE
Android Release app crashes on start up

### ISSUE THREAD

**Issue by webalexx** [AmolGangadhare/flutter_barcode_scanner#106]
**Describe the bug**
The old bug takes place again 
(https://github.com/AmolGangadhare/flutter_barcode_scanner/issues/65)

with 
Flutter version: 1.17.5
flutter_barcode_scanner: 1.0.0

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.namespace.100/com.namespace.100.MainActivity}: java.lang.ClassCastException: com.namespace.100.MainActivity cannot be cast to io.flutter.embedding.android.d
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3304)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3443)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2040)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7520)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
Caused by: java.lang.ClassCastException: com.namespace.100.MainActivity cannot be cast to io.flutter.embedding.android.d
	at com.amolg.flutterbarcodescanner.FlutterBarcodeScannerPlugin.a(Unknown Source:35)
	at f.a.c.a.b(Unknown Source:31)
	at com.namespace.100.MainActivity.onCreate(Unknown Source:3)
	at android.app.Activity.performCreate(Activity.java:7893)
	at android.app.Activity.performCreate(Activity.java:7880)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3279)
	... 11 more

**To Reproduce**
1. try to start app on any emulator's version

**Expected behavior**

**Screenshots**
<img width="1447" alt="Screenshot 2020-07-06 at 16 26 23" src="https://user-images.githubusercontent.com/17197479/86604341-8d56b380-bfa5-11ea-87aa-ca436a0140c2.png">

**Smartphone (please complete the following information):**
 - any android and ios emulator

**Additional context**

**Comment by tc14077** [comment]
Is it correlated with my issue (#103)? I face this issue too after I updated the package version to ^1.0.0

**Comment by msandwidi** [comment]
I have the same issue when upgrading from 0.7.1 to 1.0.0.

**Comment by AmolGangadhare** [comment]
@webalexx 
what is flutter SDK version you are using currently?

This issue is unfortunate as this issue was fixed with the migration guide provided by the flutter team.

**Comment by soliven25** [comment]
@AmolGangadhare 
I have the same issue too. Which migration guide are you referring to?

I'm using below version. Thanks~

Flutter 1.17.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 8af6b2f038 (4 weeks ago) • 2020-06-30 12:53:55 -0700
Engine • revision ee76268252
Tools • Dart 2.8.4

**Comment by soliven25** [comment]
https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects 
I followed the instruction above, and it solved my problem.

**Comment by AmolGangadhare** [comment]
Is this issue still persists on Flutter 2.0?

**Comment by msandwidi** [comment]
> 
> 
> Is this issue still persists on Flutter 2.0?

Mine is solved. Thank you

**Comment by mahdinazmi** [comment]
> 
> 
> > Is this issue still persists on Flutter 2.0?
> 
> Mine is solved. Thank you

How did you solve this problem?
