### ISSUE TITLE
Not working for iOS

### ISSUE THREAD

**Issue by NTMS2017** [AmolGangadhare/flutter_barcode_scanner#12]
I am not sure where to post, so please bear with me. I follow the plugin documentation and created new project using IntelliJ and I choose swift for my project. It worked perfectly for android but I am having issue to do it for iOS. When I try to build for iOS using iPhone 6 I got below error.

Any idea why I am having this issues?

**Error:**

```
Launching lib/main.dart on iPhone in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode ...
Running pod install...
CocoaPods' output:
↳
      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)

    Fetching external sources
    -> Fetching podspec for `Flutter` from `.symlinks/flutter/ios`
    -> Fetching podspec for `flutter_barcode_scanner` from `.symlinks/plugins/flutter_barcode_scanner/ios`
    -> Fetching podspec for `image_crop` from `.symlinks/plugins/image_crop/ios`
    -> Fetching podspec for `image_picker` from `.symlinks/plugins/image_picker/ios`
    -> Fetching podspec for `path_provider` from `.symlinks/plugins/path_provider/ios`

    Resolving dependencies of `Podfile`
    [!] CocoaPods could not find compatible versions for pod "flutter_barcode_scanner":
      In Podfile:
        flutter_barcode_scanner (from `.symlinks/plugins/flutter_barcode_scanner/ios`)

    Specs satisfying the `flutter_barcode_scanner (from `.symlinks/plugins/flutter_barcode_scanner/ios`)` dependency were found, but they required a higher minimum deployment target.

    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:328:in `raise_error_unless_state'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:310:in `block in unwind_for_conflict'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:308:in `tap'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:308:in `unwind_for_conflict'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:684:in `attempt_to_activate'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:254:in `process_topmost_state'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:182:in `resolve'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/molinillo-0.6.6/lib/molinillo/resolver.rb:43:in `resolve'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/resolver.rb:123:in `resolve'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:781:in `block in resolve_dependencies'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/user_interface.rb:64:in `section'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:779:in `resolve_dependencies'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:88:in `analyze'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:243:in `analyze'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:154:in `block in resolve_dependencies'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/user_interface.rb:64:in `section'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:153:in `resolve_dependencies'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:116:in `install!'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/command/install.rb:41:in `run'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/command.rb:52:in `run'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/bin/pod:55:in `<top (required)>'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/bin/pod:22:in `load'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/bin/pod:22:in `<main>'

Error output from CocoaPods:
↳

    [!] Automatically assigning platform `ios` with version `8.0` on target `Runner` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

Finished with error: Error running pod install
```

**Comment by AmolGangadhare** [comment]
Hi, 
In XCode, please set `Deployment Target` to **10** for the project, also set swift version to the latest and try again if the issue persist.

**Comment by NTMS2017** [comment]
thnaks, its working

**Comment by chiragmittal19** [comment]
I've minimum deployment target set to 10 swift version set to 5. Still receiving this error -
```
[!] CocoaPods could not find compatible versions for pod "flutter_barcode_scanner":
      In Podfile:
        flutter_barcode_scanner (from `.symlinks/plugins/flutter_barcode_scanner/ios`)

    Specs satisfying the `flutter_barcode_scanner (from `.symlinks/plugins/flutter_barcode_scanner/ios`)` dependency were found, but they required a higher minimum deployment target.
```

**Comment by zeshanmusaw** [comment]
The plugin requires you to set your ios deployment target to 11

from the plugin's docs
IOS - Requires Swift support

Deployment target : 11
To solve this, open your Podfile at ios/Podfile and change the deployment target to 11.

change the second line of your Podfile from

# platform :ios, '9.0'
to

platform :ios, '11.0'
make sure it's not commented i.e there's no # in front of the line

**Comment by igoreliasm** [comment]
@zeshanmusaw why in the section (2. Adding to existing flutter app:) is saying to use minimum deployment target to 10?
It's right?

**Comment by pmartelletti** [comment]
@AmolGangadhare same issue - target to 10 won't work, needs to be 11.

**Comment by GusRodrigues86** [comment]
Documentation is outdated. Use target to iOS 11

**Comment by praharshbhatt** [comment]
Update: the new documentation recommends to use the Deployment Target to 12.
https://pub.dev/packages/flutter_barcode_scanner#ios---requires-swift-support

**Comment by zeshanmusaw** [comment]
> @zeshanmusaw why in the section (2. Adding to existing flutter app:) is saying to use minimum deployment target to 10?
> It's right?

yes you can set to 11.0 or make sure this is not commented
