### ISSUE TITLE
Black screen and app crash on Android 9 Flutter 1.20

### ISSUE THREAD

**Issue by JamesBewley** [AmolGangadhare/flutter_barcode_scanner#120]
**Describe the bug**
Once the barcode scanner is launched only a black screen is displayed.  Pressing anywhere on the black screen results in a null pointer exception and the app crashes.

**To Reproduce**
1. Launch the barcode scanner.
2. Press the black screen.

**Expected behavior**
Barcode scanning screen and no crash.

**Smartphone (please complete the following information):**
 - Device: Moto G6
 - OS: Android 9
 - Flutter Version 1.20.2

**Comment by JamesBewley** [comment]
Trace

`Launching lib/main.dart on moto g 6 in debug mode...
✓ Built build/app/outputs/flutter-apk/app-debug.apk.
Installing build/app/outputs/flutter-apk/app.apk...
Connecting to VM Service at ws://127.0.0.1:51340/pxiPybYzQws=/ws
I/flutter (28522): unhandled element metadata; Picture key: AssetBundlePictureKey(bundle: PlatformAssetBundle#edeb0(), name: "assets/images/logo.svg", colorFilter: null)
I/flutter (28522): unhandled element sodipodi:namedview; Picture key: AssetBundlePictureKey(bundle: PlatformAssetBundle#edeb0(), name: "assets/images/logo.svg", colorFilter: null)
I/OpenGLRenderer(28522): Initialized EGL, version 1.4
D/OpenGLRenderer(28522): Swap behavior 2
I/flutter (28522): Launching QR scanner
W/ActivityThread(28522): handleWindowVisibility: no activity for token android.os.BinderProxy@e473fd
W/.app.app(28522): Accessing hidden method Landroid/graphics/drawable/Drawable;->getOpticalInsets()Landroid/graphics/Insets; (light greylist, linking)
W/.app.app(28522): Accessing hidden field Landroid/graphics/Insets;->left:I (light greylist, linking)
W/.app.app(28522): Accessing hidden field Landroid/graphics/Insets;->right:I (light greylist, linking)
W/.app.app(28522): Accessing hidden field Landroid/graphics/Insets;->top:I (light greylist, linking)
W/.app.app(28522): Accessing hidden field Landroid/graphics/Insets;->bottom:I (light greylist, linking)
W/.app.app(28522): Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (light greylist, reflection)
W/.app.app(28522): Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (light greylist, reflection)
E/InputEventReceiver(28522): Exception dispatching input event.
E/MessageQueue-JNI(28522): Exception in MessageQueue callback: handleReceiveCallback
E/MessageQueue-JNI(28522): java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.view.ScaleGestureDetector.onTouchEvent(android.view.MotionEvent)' on a null object reference
E/MessageQueue-JNI(28522): 	at com.amolg.flutterbarcodescanner.BarcodeCaptureActivity.onTouchEvent(BarcodeCaptureActivity.java:180)
E/MessageQueue-JNI(28522): 	at android.app.Activity.dispatchTouchEvent(Activity.java:3411)
E/MessageQueue-JNI(28522): 	at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
E/MessageQueue-JNI(28522): 	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:437)
E/MessageQueue-JNI(28522): 	at android.view.View.dispatchPointerEvent(View.java:12755)
E/MessageQueue-JNI(28522): 	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5151)
E/MessageQueue-JNI(28522): 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4954)
E/MessageQueue-JNI(28522): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4471)
E/MessageQueue-JNI(28522): 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4524)
E/MessageQueue-JNI(28522): 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4490)
E/MessageQueue-JNI(28522): 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4630)
E/MessageQueue-JNI(28522): 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4498)
E/MessageQueue-JNI(28522): 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4687)
E/MessageQueue-JNI(28522): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4471)
E/MessageQueue-JNI(28522): 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4524)
E/MessageQueue-JNI(28522): 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4490)
E/MessageQueue-JNI(28522): 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4498)
E/MessageQueue-JNI(28522): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4471)
E/MessageQueue-JNI(28522): 	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7197)
E/MessageQueue-JNI(28522): 	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7131)
E/MessageQueue-JNI(28522): 	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7092)
E/MessageQueue-JNI(28522): 	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7300)
E/MessageQueue-JNI(28522): 	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:193)
E/MessageQueue-JNI(28522): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MessageQueue-JNI(28522): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/MessageQueue-JNI(28522): 	at android.os.Looper.loop(Looper.java:160)
E/MessageQueue-JNI(28522): 	at android.app.ActivityThread.main(ActivityThread.java:6923)
E/MessageQueue-JNI(28522): 	at java.lang.reflect.Method.invoke(Native Method)
E/MessageQueue-JNI(28522): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/MessageQueue-JNI(28522): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:870)
D/AndroidRuntime(28522): Shutting down VM
E/AndroidRuntime(28522): FATAL EXCEPTION: main
E/AndroidRuntime(28522): Process: com.company.app, PID: 28522
E/AndroidRuntime(28522): java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.view.ScaleGestureDetector.onTouchEvent(android.view.MotionEvent)' on a null object reference
E/AndroidRuntime(28522): 	at com.amolg.flutterbarcodescanner.BarcodeCaptureActivity.onTouchEvent(BarcodeCaptureActivity.java:180)
E/AndroidRuntime(28522): 	at android.app.Activity.dispatchTouchEvent(Activity.java:3411)
E/AndroidRuntime(28522): 	at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
E/AndroidRuntime(28522): 	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:437)
E/AndroidRuntime(28522): 	at android.view.View.dispatchPointerEvent(View.java:12755)
E/AndroidRuntime(28522): 	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5151)
E/AndroidRuntime(28522): 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4954)
E/AndroidRuntime(28522): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4471)
E/AndroidRuntime(28522): 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4524)
E/AndroidRuntime(28522): 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4490)
E/AndroidRuntime(28522): 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4630)
E/AndroidRuntime(28522): 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4498)
E/AndroidRuntime(28522): 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4687)
E/AndroidRuntime(28522): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4471)
E/AndroidRuntime(28522): 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4524)
E/AndroidRuntime(28522): 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4490)
E/AndroidRuntime(28522): 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4498)
E/AndroidRuntime(28522): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4471)
E/AndroidRuntime(28522): 	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7197)
E/AndroidRuntime(28522): 	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7131)
E/AndroidRuntime(28522): 	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7092)
E/AndroidRuntime(28522): 	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7300)
E/AndroidRuntime(28522): 	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:193)
E/AndroidRuntime(28522): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/AndroidRuntime(28522): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/AndroidRuntime(28522): 	at android.os.Looper.loop(Looper.java:160)
E/AndroidRuntime(28522): 	at android.app.ActivityThread.main(ActivityThread.java:6923)
E/AndroidRuntime(28522): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(28522): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/AndroidRuntime(28522): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:870)
I/Process (28522): Sending signal. PID: 28522 SIG: 9
Lost connection to device.
Exited (sigterm)
`

**Comment by JamesBewley** [comment]
The following exception is being thrown in the onCreate method but isn't being handled

`E/BCActivity:onCreate(): onCreate: Binary XML file line #15: Binary XML file line #15: Error inflating class com.amolg.flutterbarcodescanner.camera.GraphicOverlay`

**Comment by JamesBewley** [comment]
Giving up and using the barcode_scan wrapper

https://pub.dev/packages/barcode_scan

**Comment by RangerOfGondor** [comment]
For anyone else that faced the same issue, the problem is because of an invalid string in the HEX COLOR property of `scanBarcode()` function. 

To rectify it, try this code given in the example:
`barcodeScanRes = await FlutterBarcodeScanner.scanBarcode(
          '#ff6666', 'Cancel', true, ScanMode.BARCODE);`

**Comment by scfabricio** [comment]
@RangerOfGondor 
I was having the same problem. I used your tip and it worked correctly. Thank you.

**Comment by AmolGangadhare** [comment]
Please check with the latest V 2.0.0 if the issue still persists?

**Comment by ali-kara** [comment]
> For anyone else that faced the same issue, the problem is because of an invalid string in the HEX COLOR property of `scanBarcode()` function.
> 
> To rectify it, try this code given in the example: `barcodeScanRes = await FlutterBarcodeScanner.scanBarcode( '#ff6666', 'Cancel', true, ScanMode.BARCODE);`

That was solved my problem. Thanks
