### ISSUE TITLE
Blank screen when trying to scan on android

### ISSUE THREAD

**Issue by felixwortmann** [AmolGangadhare/flutter_barcode_scanner#134]
**Describe the bug**
I try to scan on android, I only get a blank screen in the background color of my app, it does not show a viewfinder or anything else. The same code works perfectly on iOS.

**Smartphone*
 - Device: Oneplus 7 Pro
 - OS: Android 10 (Oxygen OS)

**Comment by adrianjagielak** [comment]
I have the same issue, here are my logs:

Smartphone

- Device: OnePlus 7 Pro
- OS: Android 10 (Pixel Experience)

Logs:
```
W/<REDACTED>( 4093): Accessing hidden method Lsun/misc/Unsafe;->putInt(Ljava/lang/Object;JI)V (greylist, linking, allowed)
W/<REDACTED>( 4093): Accessing hidden method Lsun/misc/Unsafe;->getInt(Ljava/lang/Object;J)I (greylist, linking, allowed)
W/<REDACTED>( 4093): Accessing hidden method Lsun/misc/Unsafe;->putLong(Ljava/lang/Object;JJ)V (greylist, linking, allowed)
W/<REDACTED>( 4093): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
W/<REDACTED>( 4093): Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, linking, allowed)
W/<REDACTED>( 4093): Accessing hidden method Lsun/misc/Unsafe;->getLong(Ljava/lang/Object;J)J (greylist,core-platform-api, linking, allowed)
W/<REDACTED>( 4093): Accessing hidden method Lsun/misc/Unsafe;->objectFieldOffset(Ljava/lang/reflect/Field;)J (greylist,core-platform-api, linking, allowed)
W/<REDACTED>( 4093): Accessing hidden method Lsun/misc/Unsafe;->putInt(Ljava/lang/Object;JI)V (greylist, linking, allowed)
W/<REDACTED>( 4093): Accessing hidden method Lsun/misc/Unsafe;->getInt(Ljava/lang/Object;J)I (greylist, linking, allowed)
W/<REDACTED>( 4093): Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, linking, allowed)
W/<REDACTED>( 4093): Accessing hidden method Lsun/misc/Unsafe;->putLong(Ljava/lang/Object;JJ)V (greylist, linking, allowed)
W/<REDACTED>( 4093): Accessing hidden method Lsun/misc/Unsafe;->allocateInstance(Ljava/lang/Class;)Ljava/lang/Object; (greylist, linking, allowed)
W/<REDACTED>( 4093): Accessing hidden method Llibcore/io/Memory;->peekLong(JZ)J (greylist, reflection, allowed)
W/<REDACTED>( 4093): Accessing hidden method Llibcore/io/Memory;->pokeLong(JJZ)V (greylist, reflection, allowed)
W/<REDACTED>( 4093): Accessing hidden method Llibcore/io/Memory;->pokeInt(JIZ)V (greylist, reflection, allowed)
W/<REDACTED>( 4093): Accessing hidden method Llibcore/io/Memory;->peekInt(JZ)I (greylist, reflection, allowed)
W/<REDACTED>( 4093): Accessing hidden method Llibcore/io/Memory;->pokeByte(JB)V (greylist, reflection, allowed)
W/<REDACTED>( 4093): Accessing hidden method Llibcore/io/Memory;->peekByte(J)B (greylist, reflection, allowed)
W/<REDACTED>( 4093): Accessing hidden method Llibcore/io/Memory;->pokeByteArray(J[BII)V (greylist, reflection, allowed)
W/<REDACTED>( 4093): Accessing hidden method Llibcore/io/Memory;->peekByteArray(J[BII)V (greylist, reflection, allowed)
W/<REDACTED>( 4093): Accessing hidden method Lsun/misc/Unsafe;->arrayBaseOffset(Ljava/lang/Class;)I (greylist,core-platform-api, linking, allowed)
W/<REDACTED>( 4093): Accessing hidden method Lsun/misc/Unsafe;->arrayIndexScale(Ljava/lang/Class;)I (greylist, linking, allowed)
W/<REDACTED>( 4093): Accessing hidden method Llibcore/io/Memory;->peekByte(J)B (greylist, linking, allowed)
W/<REDACTED>( 4093): Accessing hidden method Lsun/misc/Unsafe;->getLong(Ljava/lang/Object;J)J (greylist,core-platform-api, reflection, allowed)
W/<REDACTED>( 4093): Accessing hidden field Ljava/nio/Buffer;->address:J (greylist, reflection, allowed)
W/<REDACTED>( 4093): Accessing hidden method Lsun/misc/Unsafe;->getInt(Ljava/lang/Object;J)I (greylist, reflection, allowed)
W/<REDACTED>( 4093): Accessing hidden method Lsun/misc/Unsafe;->putInt(Ljava/lang/Object;JI)V (greylist, reflection, allowed)
W/<REDACTED>( 4093): Accessing hidden method Lsun/misc/Unsafe;->getLong(Ljava/lang/Object;J)J (greylist,core-platform-api, reflection, allowed)
W/<REDACTED>( 4093): Accessing hidden method Lsun/misc/Unsafe;->putLong(Ljava/lang/Object;JJ)V (greylist, reflection, allowed)
W/<REDACTED>( 4093): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, reflection, allowed)
W/<REDACTED>( 4093): Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, reflection, allowed)
W/<REDACTED>( 4093): Accessing hidden method Lsun/misc/Unsafe;->getUnsafe()Lsun/misc/Unsafe; (greylist,core-platform-api, linking, allowed)
W/<REDACTED>( 4093): Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, linking, allowed)
W/<REDACTED>( 4093): Accessing hidden method Lsun/misc/Unsafe;->compareAndSwapObject(Ljava/lang/Object;JLjava/lang/Object;Ljava/lang/Object;)Z (greylist, linking, allowed)
W/<REDACTED>( 4093): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
W/<REDACTED>( 4093): Accessing hidden method Lsun/misc/Unsafe;->getInt(Ljava/lang/Object;J)I (greylist, linking, allowed)
W/<REDACTED>( 4093): Accessing hidden method Lsun/misc/Unsafe;->getLong(Ljava/lang/Object;J)J (greylist,core-platform-api, linking, allowed)
W/<REDACTED>( 4093): Accessing hidden method Lsun/misc/Unsafe;->putInt(Ljava/lang/Object;JI)V (greylist, linking, allowed)
W/<REDACTED>( 4093): Accessing hidden method Lsun/misc/Unsafe;->putLong(Ljava/lang/Object;JJ)V (greylist, linking, allowed)
W/<REDACTED>( 4093): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
W/<REDACTED>( 4093): Accessing hidden method Lsun/misc/Unsafe;->getInt(Ljava/lang/Object;J)I (greylist, linking, allowed)
W/<REDACTED>( 4093): Accessing hidden method Lsun/misc/Unsafe;->putInt(Ljava/lang/Object;JI)V (greylist, linking, allowed)
W/<REDACTED>( 4093): Accessing hidden method Lsun/misc/Unsafe;->getInt(Ljava/lang/Object;J)I (greylist, linking, allowed)
W/<REDACTED>( 4093): Accessing hidden method Lsun/misc/Unsafe;->putLong(Ljava/lang/Object;JJ)V (greylist, linking, allowed)
W/<REDACTED>( 4093): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
W/<REDACTED>( 4093): Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, linking, allowed)
W/<REDACTED>( 4093): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
W/<REDACTED>( 4093): Accessing hidden method Lsun/misc/Unsafe;->getLong(Ljava/lang/Object;J)J (greylist,core-platform-api, linking, allowed)
W/<REDACTED>( 4093): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
W/<REDACTED>( 4093): Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, linking, allowed)
W/<REDACTED>( 4093): Accessing hidden method Lsun/misc/Unsafe;->getInt(Ljava/lang/Object;J)I (greylist, linking, allowed)
W/<REDACTED>( 4093): Accessing hidden method Lsun/misc/Unsafe;->putInt(Ljava/lang/Object;JI)V (greylist, linking, allowed)
E/GoogleMapController( 4093): Cannot enable MyLocation layer as location permissions are not granted
W/<REDACTED>( 4093): Accessing hidden field Ljava/nio/Buffer;->position:I (greylist, JNI, allowed)
W/<REDACTED>( 4093): Accessing hidden field Ljava/nio/Buffer;->limit:I (greylist, JNI, allowed)
W/<REDACTED>( 4093): Accessing hidden field Ljava/nio/Buffer;->_elementSizeShift:I (greylist, JNI, allowed)
W/<REDACTED>( 4093): Accessing hidden method Lsun/misc/Unsafe;->putLong(Ljava/lang/Object;JJ)V (greylist, linking, allowed)
W/<REDACTED>( 4093): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
W/<REDACTED>( 4093): Accessing hidden method Lsun/misc/Unsafe;->getLong(Ljava/lang/Object;J)J (greylist,core-platform-api, linking, allowed)
W/<REDACTED>( 4093): Accessing hidden method Lsun/misc/Unsafe;->putInt(Ljava/lang/Object;JI)V (greylist, linking, allowed)
W/<REDACTED>( 4093): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
W/<REDACTED>( 4093): Accessing hidden method Lsun/misc/Unsafe;->putLong(Ljava/lang/Object;JJ)V (greylist, linking, allowed)
W/DynamiteModule( 4093): Local module descriptor class for com.google.android.gms.googlecertificates not found.
I/DynamiteModule( 4093): Considering local module com.google.android.gms.googlecertificates:0 and remote module com.google.android.gms.googlecertificates:6
I/DynamiteModule( 4093): Selected remote version of com.google.android.gms.googlecertificates, version >= 6
W/<REDACTED>( 4093): ClassLoaderContext type mismatch. expected=PCL, found=DLC (PCL[] | DLC[];PCL[/data/app/<REDACTED>-Huv5h9ccuQkH6AFbmHpu0A==/base.apk*4226466371:/data/app/<REDACTED>-Huv5h9ccuQkH6AFbmHpu0A==/base.apk!classes2.dex*3361995940:/data/app/<REDACTED>-Huv5h9ccuQkH6AFbmHpu0A==/base.apk!classes3.dex*2924507559:/data/app/<REDACTED>-Huv5h9ccuQkH6AFbmHpu0A==/base.apk!classes4.dex*1456478842:/data/app/<REDACTED>-Huv5h9ccuQkH6AFbmHpu0A==/base.apk!classes5.dex*340913753:/data/app/<REDACTED>-Huv5h9ccuQkH6AFbmHpu0A==/base.apk!classes6.dex*2557471491:/data/app/<REDACTED>-Huv5h9ccuQkH6AFbmHpu0A==/base.apk!classes7.dex*289347158]{PCL[/system/framework/org.apache.http.legacy.jar*2680228128]})
W/<REDACTED>( 4093): Found duplicate classes, falling back to extracting from APK : /data/user_de/0/com.google.android.gms/app_chimera/m/00000042/GoogleCertificates.apk
W/<REDACTED>( 4093): NOTE: This wastes RAM and hurts startup performance.
W/<REDACTED>( 4093): Found duplicated class when checking oat files: 'Landroid/support/v4/media/MediaBrowserCompat$CustomActionResultReceiver;' in /data/app/<REDACTED>-Huv5h9ccuQkH6AFbmHpu0A==/base.apk and /data/user_de/0/com.google.android.gms/app_chimera/m/00000042/GoogleCertificates.apk
W/<REDACTED>( 4093): 
W/<REDACTED>( 4093): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
W/<REDACTED>( 4093): Accessing hidden method Lsun/misc/Unsafe;->getLong(Ljava/lang/Object;J)J (greylist,core-platform-api, linking, allowed)
W/<REDACTED>( 4093): Accessing hidden method Lsun/misc/Unsafe;->putLong(Ljava/lang/Object;JJ)V (greylist, linking, allowed)
W/ActivityThread( 4093): handleWindowVisibility: no activity for token android.os.BinderProxy@7748dcd
W/<REDACTED>( 4093): Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (greylist, reflection, allowed)
W/<REDACTED>( 4093): Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (greylist, reflection, allowed)
W/<REDACTED>( 4093): Accessing hidden method Lsun/misc/Unsafe;->putLong(Ljava/lang/Object;JJ)V (greylist, linking, allowed)
E/InputEventReceiver( 4093): Exception dispatching input event.
E/MessageQueue-JNI( 4093): Exception in MessageQueue callback: handleReceiveCallback
E/MessageQueue-JNI( 4093): java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.view.ScaleGestureDetector.onTouchEvent(android.view.MotionEvent)' on a null object reference
E/MessageQueue-JNI( 4093): 	at com.amolg.flutterbarcodescanner.BarcodeCaptureActivity.onTouchEvent(BarcodeCaptureActivity.java:180)
E/MessageQueue-JNI( 4093): 	at android.app.Activity.dispatchTouchEvent(Activity.java:4014)
E/MessageQueue-JNI( 4093): 	at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
E/MessageQueue-JNI( 4093): 	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:423)
E/MessageQueue-JNI( 4093): 	at android.view.View.dispatchPointerEvent(View.java:14219)
E/MessageQueue-JNI( 4093): 	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5656)
E/MessageQueue-JNI( 4093): 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5455)
E/MessageQueue-JNI( 4093): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4958)
E/MessageQueue-JNI( 4093): 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5011)
E/MessageQueue-JNI( 4093): 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4977)
E/MessageQueue-JNI( 4093): 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5117)
E/MessageQueue-JNI( 4093): 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4985)
E/MessageQueue-JNI( 4093): 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5174)
E/MessageQueue-JNI( 4093): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4958)
E/MessageQueue-JNI( 4093): 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5011)
E/MessageQueue-JNI( 4093): 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4977)
E/MessageQueue-JNI( 4093): 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4985)
E/MessageQueue-JNI( 4093): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4958)
E/MessageQueue-JNI( 4093): 	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7679)
E/MessageQueue-JNI( 4093): 	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7648)
E/MessageQueue-JNI( 4093): 	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7609)
E/MessageQueue-JNI( 4093): 	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7804)
E/MessageQueue-JNI( 4093): 	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:188)
E/MessageQueue-JNI( 4093): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MessageQueue-JNI( 4093): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/MessageQueue-JNI( 4093): 	at android.os.Looper.loop(Looper.java:174)
E/MessageQueue-JNI( 4093): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/MessageQueue-JNI( 4093): 	at java.lang.reflect.Method.invoke(Native Method)
E/MessageQueue-JNI( 4093): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
E/MessageQueue-JNI( 4093): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
D/AndroidRuntime( 4093): Shutting down VM
E/AndroidRuntime( 4093): FATAL EXCEPTION: main
E/AndroidRuntime( 4093): Process: <REDACTED>, PID: 4093
E/AndroidRuntime( 4093): java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.view.ScaleGestureDetector.onTouchEvent(android.view.MotionEvent)' on a null object reference
E/AndroidRuntime( 4093): 	at com.amolg.flutterbarcodescanner.BarcodeCaptureActivity.onTouchEvent(BarcodeCaptureActivity.java:180)
E/AndroidRuntime( 4093): 	at android.app.Activity.dispatchTouchEvent(Activity.java:4014)
E/AndroidRuntime( 4093): 	at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
E/AndroidRuntime( 4093): 	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:423)
E/AndroidRuntime( 4093): 	at android.view.View.dispatchPointerEvent(View.java:14219)
E/AndroidRuntime( 4093): 	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5656)
E/AndroidRuntime( 4093): 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5455)
E/AndroidRuntime( 4093): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4958)
E/AndroidRuntime( 4093): 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5011)
E/AndroidRuntime( 4093): 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4977)
E/AndroidRuntime( 4093): 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5117)
E/AndroidRuntime( 4093): 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4985)
E/AndroidRuntime( 4093): 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5174)
E/AndroidRuntime( 4093): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4958)
E/AndroidRuntime( 4093): 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5011)
E/AndroidRuntime( 4093): 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4977)
E/AndroidRuntime( 4093): 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4985)
E/AndroidRuntime( 4093): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4958)
E/AndroidRuntime( 4093): 	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7679)
E/AndroidRuntime( 4093): 	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7648)
E/AndroidRuntime( 4093): 	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7609)
E/AndroidRuntime( 4093): 	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7804)
E/AndroidRuntime( 4093): 	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:188)
E/AndroidRuntime( 4093): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/AndroidRuntime( 4093): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/AndroidRuntime( 4093): 	at android.os.Looper.loop(Looper.java:174)
E/AndroidRuntime( 4093): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/AndroidRuntime( 4093): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 4093): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
E/AndroidRuntime( 4093): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
W/<REDACTED>( 4093): Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, linking, allowed)
```

**Comment by TimVogt-vlab** [comment]
I had a similar error. The reason was that I tried to use a transparent color for the scan line. I solved this by just using a simple hex color string '#FF0000'.

**Comment by AmolGangadhare** [comment]
Thanks for the update @TimVogt-vlab, hope this might have helped to resolve the issue.

@adrianjagielak @felixwortmann Is the issue still there? 
Can you add some code you tried?

**Comment by nsilvah** [comment]
The issue is still there.

**Comment by nsilvah** [comment]
I found the fix. The app was crashing because the color parameter I was using was "ffffff" instead of "#ffffff".

**Comment by SantiMedica** [comment]
hahahah i had the same problem xddd

**Comment by qasim90** [comment]
As @nsilvah mentioned, this issue happens if you provide wrong color code. In my case I was using '#fff' instead of '#ffffff'. Issue can be closed. Should be replaced with `Color` object or apply validation on hex color code for wrong colors to better handle this.
