### ISSUE TITLE
Scan not working on lower-end phones

### ISSUE THREAD

**Issue by synw** [AmolGangadhare/flutter_barcode_scanner#15]
**Problem**
The scan does not work on lower-end phones. The camera does not give a good enough resolution and it does not grab the barcode.

**Potential solution**
Use the front camera to scan. I used this solution with another lib and it worked, but this lib now being unmaintained I am looking for an alternative. It would be great to be able to scan with the front camera. 

**Alternative**
Add an option to manually manage the resolution. As the scan with the back camera works in some other Android apps it might be a resolution selection problem

**Comment by AmolGangadhare** [comment]
Hi,
Did you face this issue only in Android or also in iOS?

**Comment by synw** [comment]
On Android with Samsumg J1 Mini (Android 5.1), Samsung Tab 4 (Android 4.4) or a no-brand cheap chinese tablet 'Android 5.0), all of several years old. I don"t know about IOS I have no device running it

**Comment by AmolGangadhare** [comment]
thanks for the details

**Comment by AmolGangadhare** [comment]
I was unable to reproduce this issue. This seems to be happening due to the camera fails to autofocus. Can you confirm the same issue in the latest release?

**Comment by synw** [comment]
I confirm the issue using the example in master. There is no autofocus, the image stays blurry on screen

**Comment by DONT-KNOW-JAVA** [comment]
I've the very same problem  with my  samsung A3 (2016)  

the autofucus works well  ; the image is  sharp      but It cannot detect any bar code

**Comment by changshasha** [comment]
how about this issue? I encounter same issue on my android 8.1 mobile

**Comment by mikymod** [comment]
Hi! I encountered this issue too on Android 7.1.2.

```
D/BarcodeNativeHandle( 7479): Cannot load feature, fall back to load dynamite module.
W/DynamiteModule( 7479): Local module descriptor class for com.google.android.gms.vision.dynamite not found.
I/DynamiteModule( 7479): Considering local module com.google.android.gms.vision.dynamite:0 and remote module com.google.android.gms.vision.dynamite:2703
I/DynamiteModule( 7479): Selected remote version of com.google.android.gms.vision.dynamite, version >= 2703
V/DynamiteModule( 7479): Dynamite loader version >= 2, using loadModule2NoCrashUtils
W/DynamiteModule( 7479): Local module descriptor class for com.google.android.gms.vision.barcode not found.
I/DynamiteModule( 7479): Considering local module com.google.android.gms.vision.barcode:0 and remote module com.google.android.gms.vision.barcode:0
E/BarcodeDetectorCreator( 7479): Error loading optional module com.google.android.gms.vision.barcode
E/BarcodeDetectorCreator( 7479): hb: No acceptable module found. Local version is 0 and remote version is 0.
E/BarcodeDetectorCreator( 7479): 	at he.d(:com.google.android.gms.dynamite_dynamitemodulesa@205016048@20.50.16 (040400-0):84)
E/BarcodeDetectorCreator( 7479): 	at com.google.android.gms.vision.barcode.ChimeraNativeBarcodeDetectorCreator.b(:com.google.android.gms.dynamite_dynamitemodulesa@205016048@20.50.16 (040400-0):2)
E/BarcodeDetectorCreator( 7479): 	at jg.newBarcodeDetector(:com.google.android.gms.dynamite_dynamitemodulesa@205016048@20.50.16 (040400-0):3)
E/BarcodeDetectorCreator( 7479): 	at com.google.android.gms.vision.barcode.ChimeraNativeBarcodeDetectorCreator.newBarcodeDetector(:com.google.android.gms.dynamite_dynamitemodulesa@205016048@20.50.16 (040400-0):0)
E/BarcodeDetectorCreator( 7479): 	at jo.u(:com.google.android.gms.dynamite_dynamitemodulesa@205016048@20.50.16 (040400-0):4)
E/BarcodeDetectorCreator( 7479): 	at an.onTransact(:com.google.android.gms.dynamite_dynamitemodulesa@205016048@20.50.16 (040400-0):4)
E/BarcodeDetectorCreator( 7479): 	at android.os.Binder.transact(Binder.java:499)
E/BarcodeDetectorCreator( 7479): 	at com.google.android.gms.internal.vision.zzb.zza(com.google.android.gms:play-services-vision-common@@19.0.0:10)
E/BarcodeDetectorCreator( 7479): 	at com.google.android.gms.internal.vision.zzk.zza(com.google.android.gms:play-services-vision@@19.0.0:6)
E/BarcodeDetectorCreator( 7479): 	at com.google.android.gms.internal.vision.zzh.zza(com.google.android.gms:play-services-vision@@19.0.0:36)
E/BarcodeDetectorCreator( 7479): 	at com.google.android.gms.internal.vision.zzn.zzp(com.google.android.gms:play-services-vision-common@@19.0.0:55)
E/BarcodeDetectorCreator( 7479): 	at com.google.android.gms.internal.vision.zzn.isOperational(com.google.android.gms:play-services-vision-common@@19.0.0:21)
E/BarcodeDetectorCreator( 7479): 	at com.google.android.gms.internal.vision.zzh.zza(com.google.android.gms:play-services-vision@@19.0.0:5)
E/BarcodeDetectorCreator( 7479): 	at com.google.android.gms.vision.barcode.BarcodeDetector.detect(com.google.android.gms:play-services-vision@@19.0.0:17)
E/BarcodeDetectorCreator( 7479): 	at com.google.android.gms.vision.Detector.receiveFrame(com.google.android.gms:play-services-vision-common@@19.0.0:11)
E/BarcodeDetectorCreator( 7479): 	at com.amolg.flutterbarcodescanner.camera.CameraSource$FrameProcessingRunnable.run(CameraSource.java:1033)
E/BarcodeDetectorCreator( 7479): 	at java.lang.Thread.run(Thread.java:761)
```

Is there any solution?

**Comment by cezaryjk** [comment]
Hi all,
I had the same issue even on Android 11.
It turned out "Google Play Services" package was missing.
Last available package requires Android 8...

Good luck!
Cezary
