### ISSUE TITLE
issue when i want to scan in android

### ISSUE THREAD

**Issue by bestheroforever** [AmolGangadhare/flutter_barcode_scanner#162]
```
Timeline: Activity_launch_request id:com.shlen time:132883890
W/art     (19947): Before Android 4.1, method android.graphics.PorterDuffColorFilter androidx.vectordrawable.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
```

**Comment by bestheroforever** [comment]
`E/AndroidRuntime(19947): 	at androidx.vectordrawable.graphics.drawable.VectorDrawableCompat.updateStateFromTypedArray(VectorDrawableCompat.java:765)
E/AndroidRuntime(19947): 	at androidx.vectordrawable.graphics.drawable.VectorDrawableCompat.inflate(VectorDrawableCompat.java:719)
E/AndroidRuntime(19947): 	at androidx.vectordrawable.graphics.drawable.VectorDrawableCompat.createFromXmlInner(VectorDrawableCompat.java:682)
E/AndroidRuntime(19947): 	at androidx.appcompat.widget.ResourceManagerInternal$VdcInflateDelegate.createFromXmlInner(ResourceManagerInternal.java:526)
E/AndroidRuntime(19947): 	at androidx.appcompat.widget.ResourceManagerInternal.loadDrawableFromDelegates(ResourceManagerInternal.java:287)
E/AndroidRuntime(19947): 	at androidx.appcompat.widget.ResourceManagerInternal.getDrawable(ResourceManagerInternal.java:139)
E/AndroidRuntime(19947): 	at androidx.appcompat.widget.ResourceManagerInternal.getDrawable(ResourceManagerInternal.java:132)
E/AndroidRuntime(19947): 	at androidx.appcompat.widget.ResourceManagerInternal.checkVectorDrawableSetup(ResourceManagerInternal.java:504)
E/AndroidRuntime(19947): 	at androidx.appcompat.widget.ResourceManagerInternal.getDrawable(ResourceManagerInternal.java:137)
E/AndroidRuntime(19947): 	at androidx.appcompat.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:411)
E/AndroidRuntime(19947): 	at androidx.appcompat.widget.TintTypedArray.getDrawableIfKnown(TintTypedArray.java:86)
E/AndroidRuntime(19947): 	at androidx.appcompat.app.AppCompatDelegateImpl.attachToWindow(AppCompatDelegateImpl.java:647)
E/AndroidRuntime(19947): 	at androidx.appcompat.app.AppCompatDelegateImpl.ensureWindow(AppCompatDelegateImpl.java:623)
E/AndroidRuntime(19947): 	at androidx.appcompat.app.AppCompatDelegateImpl.onCreate(AppCompatDelegateImpl.java:350)
E/AndroidRuntime(19947): 	at androidx.appcompat.app.AppCompatActivity.onCreate(AppCompatActivity.java:105)
E/AndroidRuntime(19947): 	at com.amolg.flutterbarcodescanner.BarcodeCaptureActivity.onCreate(BarcodeCaptureActivity.java:107)
E/AndroidRuntime(19947): 	at android.app.Activity.performCreate(Activity.java:6876)
E/AndroidRuntime(19947): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1135)
E/AndroidRuntime(19947): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3206)
E/AndroidRuntime(19947): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3349)
E/AndroidRuntime(19947): 	at android.app.ActivityThread.access$1100(ActivityThread.java:221)
E/AndroidRuntime(19947): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794)
E/AndroidRuntime(19947): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(19947): 	at android.os.Looper.loop(Looper.java:158)
E/AndroidRuntime(19947): 	at android.app.ActivityThread.main(ActivityThread.java:7225)
E/AndroidRuntime(19947): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(19947): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
E/AndroidRuntime(19947): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
I/Process (19947): Sending signal. PID: 19947 SIG: 9
`
