### ISSUE TITLE
Shutting down VM

### ISSUE THREAD

**Issue by eliasayele** [AmolGangadhare/flutter_barcode_scanner#166]
### after nullsafety(flutter_barcode_scanner: ^2.0.0-nullsafety.0) when scan finish it shows this error message and shutdown the app

D/AndroidRuntime(22909): Shutting down VM
E/AndroidRuntime(22909): FATAL EXCEPTION: main
E/AndroidRuntime(22909): Process: com.example.barcoder, PID: 22909
E/AndroidRuntime(22909): java.lang.RuntimeException: Unable to destroy activity {com.example.barcoder/com.amolg.flutterbarcodescanner.BarcodeCaptureActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Thread$State java.lang.Thread.getState()' on a null object reference
E/AndroidRuntime(22909): 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4720)
E/AndroidRuntime(22909): 	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4743)
E/AndroidRuntime(22909): 	at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:39)
E/AndroidRuntime(22909): 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
E/AndroidRuntime(22909): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
E/AndroidRuntime(22909): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1960)
E/AndroidRuntime(22909): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(22909): 	at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime(22909): 	at android.app.ActivityThread.main(ActivityThread.java:7094)
E/AndroidRuntime(22909): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(22909): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
E/AndroidRuntime(22909): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
E/AndroidRuntime(22909): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Thread$State java.lang.Thread.getState()' on a null object reference
E/AndroidRuntime(22909): 	at com.amolg.flutterbarcodescanner.camera.CameraSource$FrameProcessingRunnable.release(CameraSource.java:967)
E/AndroidRuntime(22909): 	at com.amolg.flutterbarcodescanner.camera.CameraSource.release(CameraSource.java:273)
E/AndroidRuntime(22909): 	at com.amolg.flutterbarcodescanner.camera.CameraSourcePreview.release(CameraSourcePreview.java:84)
E/AndroidRuntime(22909): 	at com.amolg.flutterbarcodescanner.BarcodeCaptureActivity.onDestroy(BarcodeCaptureActivity.java:266)
E/AndroidRuntime(22909): 	at android.app.Activity.performDestroy(Activity.java:7697)
E/AndroidRuntime(22909): 	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1310)
E/AndroidRuntime(22909): 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4705)
E/AndroidRuntime(22909): 	... 11 more
I/Process (22909): Sending signal. PID: 22909 SIG: 9
Lost connection to device.

### flutter doctor -v result

Microsoft Windows [Version 10.0.19042.867]
(c) 2020 Microsoft Corporation. All rights reserved.
C:\flutterapps\barcoder>flutter doctor -v
[√] Flutter (Channel stable, 2.0.1, on Microsoft Windows [Version 10.0.19042.867], locale en-US)
    • Flutter version 2.0.1 at C:\flutter
    • Framework revision c5a4b4029c (11 days ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.52.1)
    • VS Code at C:\Users\samrawit ayele\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.20.0

[√] Connected device (3 available)
    • SM J415F (mobile) • 69facea2 • android-arm    • Android 9 (API 28)
    • Chrome (web)      • chrome   • web-javascript • Google Chrome 89.0.4389.82
    • Edge (web)        • edge     • web-javascript • Microsoft Edge 89.0.774.50

• No issues found!

**Comment by excode** [comment]
I am getting this error. 



D/BarcodeNativeHandle( 2319): Broadcasting download intent for dependency barcode
W/BarcodeNativeHandle( 2319): Native handle not yet available. Reverting to no-op handle.
W/DynamiteModule( 2319): Local module descriptor class for com.google.android.gms.vision.dynamite.barcode not found.
I/DynamiteModule( 2319): Considering local module com.google.android.gms.vision.dynamite.barcode:0 and remote module com.google.android.gms.vision.dynamite.barcode:0
D/BarcodeNativeHandle( 2319): Cannot load feature, fall back to load dynamite module.
W/DynamiteModule( 2319): Local module descriptor class for com.google.android.gms.vision.barcode not found.
I/DynamiteModule( 2319): Considering local module com.google.android.gms.vision.barcode:0 and remote module com.google.android.gms.vision.barcode:0
E/Vision  ( 2319): Error loading module com.google.android.gms.vision.barcode optional module true: com.google.android.gms.dynamite.DynamiteModule$LoadingException: No acceptable module found. Local version is 0 and remote version is 0.
D/EGL_emulation( 2319): eglMakeCurrent: 0xa9857380: ver 3 0 (tinfo 0xa97a1060)
D/AndroidRuntime( 2319): Shutting down VM
E/AndroidRuntime( 2319): FATAL EXCEPTION: main
E/AndroidRuntime( 2319): Process: net.excode.mypaaa, PID: 2319
E/AndroidRuntime( 2319): java.lang.RuntimeException: Could not find requested camera.
E/AndroidRuntime( 2319): 	at com.amolg.flutterbarcodescanner.camera.CameraSource.createCamera(CameraSource.java:690)
E/AndroidRuntime( 2319): 	at com.amolg.flutterbarcodescanner.camera.CameraSource.start(CameraSource.java:324)
E/AndroidRuntime( 2319): 	at com.amolg.flutterbarcodescanner.camera.CameraSourcePreview.startIfReady(CameraSourcePreview.java:92)
E/AndroidRuntime( 2319): 	at com.amolg.flutterbarcodescanner.camera.CameraSourcePreview.access$200(CameraSourcePreview.java:34)
E/AndroidRuntime( 2319): 	at com.amolg.flutterbarcodescanner.camera.CameraSourcePreview$SurfaceCallback.surfaceCreated(CameraSourcePreview.java:115)
E/AndroidRuntime( 2319): 	at android.view.SurfaceView.updateWindow(SurfaceView.java:582)
E/AndroidRuntime( 2319): 	at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:177)
E/AndroidRuntime( 2319): 	at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:944)
E/AndroidRuntime( 2319): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2055)
E/AndroidRuntime( 2319): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
E/AndroidRuntime( 2319): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6013)
E/AndroidRuntime( 2319): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
E/AndroidRuntime( 2319): 	at android.view.Choreographer.doCallbacks(Choreographer.java:670)
E/AndroidRuntime( 2319): 	at android.view.Choreographer.doFrame(Choreographer.java:606)
E/AndroidRuntime( 2319): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
E/AndroidRuntime( 2319): 	at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime( 2319): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime( 2319): 	at android.os.Looper.loop(Looper.java:148)
E/AndroidRuntime( 2319): 	at android.app.ActivityThread.main(ActivityThread.java:5417)
E/AndroidRuntime( 2319): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 2319): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
E/AndroidRuntime( 2319): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
I/Process ( 2319): Sending signal. PID: 2319 SIG: 9

**Comment by AmolGangadhare** [comment]
Please try with V 2.0.0

**Comment by JinG312** [comment]
@AmolGangadhare I'm currently using V2.0.0 still having this error. 

Error:
D/AndroidRuntime(15695): Shutting down VM
E/AndroidRuntime(15695): FATAL EXCEPTION: main
E/AndroidRuntime(15695): Process: com.example.htosafe, PID: 15695
E/AndroidRuntime(15695): java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
E/AndroidRuntime(15695): 	at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:843)
E/AndroidRuntime(15695): 	at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:806)
E/AndroidRuntime(15695): 	at androidx.appcompat.app.AppCompatDelegateImpl.onPostCreate(AppCompatDelegateImpl.java:527)
E/AndroidRuntime(15695): 	at androidx.appcompat.app.AppCompatActivity.onPostCreate(AppCompatActivity.java:127)
E/AndroidRuntime(15695): 	at android.app.Instrumentation.callActivityOnPostCreate(Instrumentation.java:1383)
E/AndroidRuntime(15695): 	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3845)
E/AndroidRuntime(15695): 	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
E/AndroidRuntime(15695): 	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
E/AndroidRuntime(15695): 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
E/AndroidRuntime(15695): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
E/AndroidRuntime(15695): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
E/AndroidRuntime(15695): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(15695): 	at android.os.Looper.loop(Looper.java:246)
E/AndroidRuntime(15695): 	at android.app.ActivityThread.main(ActivityThread.java:8512)
E/AndroidRuntime(15695): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(15695): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
E/AndroidRuntime(15695): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1139)
I/Process (15695): Sending signal. PID: 15695 SIG: 9
Lost connection to device.
Exited (sigterm)
