### ISSUE TITLE
flutter app crash when running in release mode (flutter run --release)

### ISSUE THREAD

**Issue by tomaszkubacki** [AmolGangadhare/flutter_barcode_scanner#188]
App using barcode scanner does not work when run in **release mode** (flutter run --release) but works perfectly well in **debug mode** (flutter run) or even **profile mode** ( flutter run  --profile )

possibly related to: [https://github.com/flutter/flutter/issues/58479](https://github.com/flutter/flutter/issues/58479)
Maybe **flutter_plugin_android_lifecycle**  needs to be bumped to **2.0.1** ?

### flutter run --release output below:
```
E/AndroidRuntime(17812): FATAL EXCEPTION: main
E/AndroidRuntime(17812): Process: net.mycompany.my_app, PID: 17812
E/AndroidRuntime(17812): java.lang.IllegalAccessError: Interface androidx.lifecycle.b implemented by class com.amolg.flutterbarcodescanner.FlutterBarcodeScannerPlugin$LifeCycleObserver is inaccessible (declaration of 'com.amolg.flutterbarcodescanner.FlutterBarcodeScannerPlugin$LifeCycleObserver' appears in /data/app/net.mycompany.my_app-dpdaPkNNVcKhAGSsE_EZ1A==/base.apk)
E/AndroidRuntime(17812):        at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(Unknown Source:9)
E/AndroidRuntime(17812):        at net.mycompany.my_app.MainActivity.A(Unknown Source:5)
E/AndroidRuntime(17812):        at io.flutter.embedding.android.f.k(Unknown Source:58)
E/AndroidRuntime(17812):        at io.flutter.embedding.android.e.onCreate(Unknown Source:13)
E/AndroidRuntime(17812):        at net.mycompany.my_app.MainActivity.onCreate(Unknown Source:0)
E/AndroidRuntime(17812):        at android.app.Activity.performCreate(Activity.java:7809)
E/AndroidRuntime(17812):        at android.app.Activity.performCreate(Activity.java:7798)
E/AndroidRuntime(17812):        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
E/AndroidRuntime(17812):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3246)
E/AndroidRuntime(17812):        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3410)
E/AndroidRuntime(17812):        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
E/AndroidRuntime(17812):        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime(17812):        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime(17812):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2017)
E/AndroidRuntime(17812):        at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime(17812):        at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime(17812):        at android.app.ActivityThread.main(ActivityThread.java:7403)
E/AndroidRuntime(17812):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(17812):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/AndroidRuntime(17812):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)

Application finished.
```

**Comment by AmolGangadhare** [comment]
The issue has been fixed with the latest release V 2.0.0.

Closing this now, feel free to open new issue
