### ISSUE TITLE
Error: MissingPluginException(No implementation found for method scanBarcode on channel flutter_barcode_scanner)

### ISSUE THREAD

**Issue by danieluac** [AmolGangadhare/flutter_barcode_scanner#197]
Error: MissingPluginException(No implementation found for method scanBarcode on channel flutter_barcode_scanner)
    at Object.throw_ [as throw] (http://localhost:54333/dart_sdk.js:5333:11)
    at MethodChannel._invokeMethod (http://localhost:54333/packages/flutter/src/services/system_channels.dart.lib.js:954:21)
    at _invokeMethod.next (<anonymous>)
    at http://localhost:54333/dart_sdk.js:39031:33
    at _RootZone.runUnary (http://localhost:54333/dart_sdk.js:38888:58)
    at _FutureListener.thenAwait.handleValue (http://localhost:54333/dart_sdk.js:33874:29)
    at handleValueCallback (http://localhost:54333/dart_sdk.js:34434:49)
    at Function._propagateToListeners (http://localhost:54333/dart_sdk.js:34472:17)
    at _Future.new.[_completeWithValue] (http://localhost:54333/dart_sdk.js:34314:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:54333/dart_sdk.js:34337:35)
    at Object._microtaskLoop (http://localhost:54333/dart_sdk.js:39175:13)
    at _startMicrotaskLoop (http://localhost:54333/dart_sdk.js:39181:13)
    at http://localhost:54333/dart_sdk.js:34688:9

**Comment by danieluac** [comment]
Why I am getting this?
just created the app, but I when try to click on button to call scanner qr, barcode... I am getting this issue in my console...

**Comment by AmolGangadhare** [comment]
Try flutter clean-> Invalidate Cache and Restart on android studio->flutter pub get.

It should resolve the issue for you.

**Comment by AmolGangadhare** [comment]
@danieluac 

Have you tried the possible solution? Is the issue persists for you?

**Comment by skyflakes05** [comment]
> Try flutter clean-> Invalidate Cache and Restart on android studio->flutter pub get.
> 
> It should resolve the issue for you.

Hi @AmolGangadhare, I also encounter this issue even after doing these steps. What else can I check for this? 

Thank you so much.

**Comment by danieluac** [comment]
I just tried, anything works @AmolGangadhare
