### ISSUE TITLE
FlutterBarcodeScannerPlugin not working

### ISSUE THREAD

**Issue by fathialamre** [AmolGangadhare/flutter_barcode_scanner#209]
java.lang.ClassCastException: com.giga.giganet.MainActivity cannot be cast to io.flutter.embedding.android.FlutterActivity
E/AndroidRuntime(14107): 	at com.amolg.flutterbarcodescanner.FlutterBarcodeScannerPlugin.createPluginSetup(FlutterBarcodeScannerPlugin.java:248)
E/AndroidRuntime(14107): 	at com.amolg.flutterbarcodescanner.FlutterBarcodeScannerPlugin.onAttachedToActivity(FlutterBarcodeScannerPlugin.java:275)
E/AndroidRuntime(14107): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.add(FlutterEngineConnectionRegistry.java:153)
E/AndroidRuntime(14107): 	at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:21)
E/AndroidRuntime(14107): 	at com.giga.giganet.MainActivity.configureFlutterEngine(MainActivity.java:12)
E/AndroidRuntime(14107): 	at io.flutter.embedding.android.FlutterFragment.configureFlutterEngine(FlutterFragment.java:1023)
E/AndroidRuntime(14107): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:180)
E/AndroidRuntime(14107): 	at io.flutter.embedding.android.FlutterFragment.onAttach(FlutterFragment.java:609)
E/AndroidRuntime(14107): 	at androidx.fragment.app.Fragment.performAttach(Fragment.java:2922)
E/AndroidRuntime(14107): 	at androidx.fragment.app.FragmentStateManager.attach(FragmentStateManager.java:464)
E/AndroidRuntime(14107): 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:275)
E/AndroidRuntime(14107): 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
E/AndroidRuntime(14107): 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
E/AndroidRuntime(14107): 	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
E/AndroidRuntime(14107): 	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3136)
E/AndroidRuntime(14107): 	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:3070)
E/AndroidRuntime(14107): 	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:251)
E/AndroidRuntime(14107): 	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:501)
E/AndroidRuntime(14107): 	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1433)
E/AndroidRuntime(14107): 	at android.app.Activity.performStart(Activity.java:7924)
E/AndroidRuntime(14107): 	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3332)
E/AndroidRuntime(14107): 	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
E/AndroidRuntime(14107): 	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
E/AndroidRuntime(14107): 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
E/AndroidRuntime(14107): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
E/AndroidRuntime(14107): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2044)
E/AndroidRuntime(14107): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime(14107): 	at android.os.Looper.loop(Looper.java:224)
E/AndroidRuntime(14107): 	at android.app.ActivityThread.main(ActivityThread.java:7560)
E/AndroidRuntime(14107): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(14107): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
E/AndroidRuntime(14107): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by alejandroPolak-1** [comment]
I had the same problem:
1) First: you need your environment sdk:> = 2.12
2) Later. I was only able to make this problem go away by changing the flutter channel to beta (flutter channel beta / flutter update / flutter pub get)
But the new problem that appears is MissingPluginException (no implementation found for scanBarcode method in flutter_barcode_scanner channel)
