### ISSUE TITLE
Caught error crash on production

### ISSUE THREAD

**Issue by pansitwattana** [AmolGangadhare/flutter_barcode_scanner#247]
Found crash when release to Play Store

Crash on Android 11 (F11 Pro)
Use Flutter 2.5.3 to build this project

`Fatal Exception: java.lang.RuntimeException: Unable to resume activity`

```
Caused by java.lang.NullPointerException: Attempt to invoke interface method 'void g.a.c.a.j$d.success(java.lang.Object)' on a null object reference
       at com.amolg.flutterbarcodescanner.FlutterBarcodeScannerPlugin.onActivityResult(FlutterBarcodeScannerPlugin.java:28)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEngineConnectionRegistry.java:25)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onActivityResult(FlutterEngineConnectionRegistry.java:15)
       at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:51)
       at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:10)
       at android.app.Activity.dispatchActivityResult(Activity.java:8469)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:5411)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4800)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4855)
       at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2345)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:264)
       at android.app.ActivityThread.main(ActivityThread.java:8282)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
```

```
Caused by java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=9001, result=0, data=null} to activity: java.lang.NullPointerException: Attempt to invoke interface method 'void g.a.c.a.j$d.success(java.lang.Object)' on a null object reference
       at android.app.ActivityThread.deliverResults(ActivityThread.java:5418)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4800)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4855)
       at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2345)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:264)
       at android.app.ActivityThread.main(ActivityThread.java:8282)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
```

**Comment by ashfevertree** [comment]
We also have this issue on Production :/

Debug builds work fine

**Comment by pansitwattana** [comment]
any updates ? also got another crash

```
java.lang.RuntimeException: 
  at android.app.ActivityThread.deliverResults (ActivityThread.java:5078)
  at android.app.ActivityThread.handleSendResult (ActivityThread.java:5120)
  at android.app.servertransaction.ActivityResultItem.execute (ActivityResultItem.java:49)
  at android.app.servertransaction.TransactionExecutor.executeCallbacks (TransactionExecutor.java:108)
  at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:68)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2199)
  at android.os.Handler.dispatchMessage (Handler.java:112)
  at android.os.Looper.loop (Looper.java:216)
  at android.app.ActivityThread.main (ActivityThread.java:7625)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:524)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:987)
Caused by: java.lang.NullPointerException: 
  at com.amolg.flutterbarcodescanner.FlutterBarcodeScannerPlugin.onActivityResult (FlutterBarcodeScannerPlugin.java:28)
  at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult (FlutterEngineConnectionRegistry.java:25)
  at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onActivityResult (FlutterEngineConnectionRegistry.java:15)
  at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult (FlutterActivityAndFragmentDelegate.java:51)
  at io.flutter.embedding.android.FlutterActivity.onActivityResult (FlutterActivity.java:10)
  at android.app.Activity.dispatchActivityResult (Activity.java:7797)
  at android.app.ActivityThread.deliverResults (ActivityThread.java:5071)
  at android.app.ActivityThread.handleSendResult (ActivityThread.java:5120)
  at android.app.servertransaction.ActivityResultItem.execute (ActivityResultItem.java:49)
  at android.app.servertransaction.TransactionExecutor.executeCallbacks (TransactionExecutor.java:108)
  at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:68)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2199)
  at android.os.Handler.dispatchMessage (Handler.java:112)
  at android.os.Looper.loop (Looper.java:216)
  at android.app.ActivityThread.main (ActivityThread.java:7625)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:524)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:987)
```

**Comment by ebraamboshra1** [comment]
any update?


`com.amolg.flutterbarcodescanner.FlutterBarcodeScannerPlugin.onActivityResult (FlutterBarcodeScannerPlugin.java:28)
io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult (FlutterEngineConnectionRegistry.java:25)
io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onActivityResult (FlutterEngineConnectionRegistry.java:20)
io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult (FlutterActivityAndFragmentDelegate.java:51)
io.flutter.embedding.android.FlutterActivity.onActivityResult (FlutterActivity.java:10)
android.app.Activity.dispatchActivityResult (Activity.java:8262)
android.app.ActivityThread.deliverResults (ActivityThread.java:4931)
android.app.ActivityThread.performResumeActivity (ActivityThread.java:4257)
android.app.ActivityThread.handleResumeActivity (ActivityThread.java:4302)
android.app.servertransaction.ResumeActivityItem.execute (ResumeActivityItem.java:52)
android.app.servertransaction.TransactionExecutor.executeLifecycleState (TransactionExecutor.java:176)
android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:97)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:2044)
android.os.Handler.dispatchMessage (Handler.java:107)
android.os.Looper.loop (Looper.java:223)
android.app.ActivityThread.main (ActivityThread.java:7562)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:539)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:950)`

**Comment by ebraamboshra1** [comment]
any update?

**Comment by gfb-47** [comment]
Same issue here
