### ISSUE TITLE
Scanner not working if no internet on a phone

### ISSUE THREAD

**Issue by brun0xon** [AmolGangadhare/flutter_barcode_scanner#25]
If you disable internet connection, scanner will not be showing
```
W/art     ( 3719): Before Android 4.1, method android.graphics.PorterDuffColorFilter androidx.vectordrawable.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
I/art     ( 3719): Rejecting re-init on previously-failed class java.lang.Class<androidx.core.view.ViewCompat$OnUnhandledKeyEventListenerWrapper>
I/art     ( 3719): Rejecting re-init on previously-failed class java.lang.Class<androidx.core.view.ViewCompat$OnUnhandledKeyEventListenerWrapper>
W/DynamiteModule( 3719): Local module descriptor class for com.google.android.gms.vision.dynamite.barcode not found.
E/ActivityThread( 3719): Failed to find provider info for com.google.android.gms.chimera
W/DynamiteModule( 3719): Failed to retrieve remote module version.
W/GooglePlayServicesUtil( 3719): Google Play Store is missing.
I/DynamiteModule( 3719): Considering local module com.google.android.gms.vision.dynamite.barcode:0 and remote module com.google.android.gms.vision.dynamite.barcode:0
D/BarcodeNativeHandle( 3719): Cannot load feature, fall back to load whole module.
W/DynamiteModule( 3719): Local module descriptor class for com.google.android.gms.vision.dynamite not found.
W/GooglePlayServicesUtil( 3719): Google Play Store is missing.
I/DynamiteModule( 3719): Considering local module com.google.android.gms.vision.dynamite:0 and remote module com.google.android.gms.vision.dynamite:0
E/BarcodeNativeHandle( 3719): Error Loading module
E/BarcodeNativeHandle( 3719): com.google.android.gms.dynamite.DynamiteModule$LoadingException: No acceptable module found. Local version is 0 and remote version is 0.
E/BarcodeNativeHandle( 3719): 	at com.google.android.gms.dynamite.DynamiteModule.load(Unknown Source)
E/BarcodeNativeHandle( 3719): 	at com.google.android.gms.internal.vision.zzm.zzq(Unknown Source)
E/BarcodeNativeHandle( 3719): 	at com.google.android.gms.internal.vision.zzg.<init>(Unknown Source)
E/BarcodeNativeHandle( 3719): 	at com.google.android.gms.vision.barcode.BarcodeDetector$Builder.build(Unknown Source)
E/BarcodeNativeHandle( 3719): 	at com.amolg.flutterbarcodescanner.BarcodeCaptureActivity.createCameraSource(BarcodeCaptureActivity.java:196)
E/BarcodeNativeHandle( 3719): 	at com.amolg.flutterbarcodescanner.BarcodeCaptureActivity.onCreate(BarcodeCaptureActivity.java:129)
E/BarcodeNativeHandle( 3719): 	at android.app.Activity.performCreate(Activity.java:5990)
E/BarcodeNativeHandle( 3719): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
E/BarcodeNativeHandle( 3719): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
E/BarcodeNativeHandle( 3719): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
E/BarcodeNativeHandle( 3719): 	at android.app.ActivityThread.access$800(ActivityThread.java:151)
E/BarcodeNativeHandle( 3719): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
E/BarcodeNativeHandle( 3719): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/BarcodeNativeHandle( 3719): 	at android.os.Looper.loop(Looper.java:135)
E/BarcodeNativeHandle( 3719): 	at android.app.ActivityThread.main(ActivityThread.java:5254)
E/BarcodeNativeHandle( 3719): 	at java.lang.reflect.Method.invoke(Native Method)
E/BarcodeNativeHandle( 3719): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/BarcodeNativeHandle( 3719): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
E/BarcodeNativeHandle( 3719): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
W/BarcodeNativeHandle( 3719): Native handle not yet available. Reverting to no-op handle.
W/DynamiteModule( 3719): Local module descriptor class for com.google.android.gms.vision.dynamite.barcode not found.
W/GooglePlayServicesUtil( 3719): Google Play Store is missing.
I/DynamiteModule( 3719): Considering local module com.google.android.gms.vision.dynamite.barcode:0 and remote module com.google.android.gms.vision.dynamite.barcode:0
D/BarcodeNativeHandle( 3719): Cannot load feature, fall back to load whole module.
W/DynamiteModule( 3719): Local module descriptor class for com.google.android.gms.vision.dynamite not found.
W/GooglePlayServicesUtil( 3719): Google Play Store is missing.
I/DynamiteModule( 3719): Considering local module com.google.android.gms.vision.dynamite:0 and remote module com.google.android.gms.vision.dynamite:0
E/BarcodeNativeHandle( 3719): Error Loading module
E/BarcodeNativeHandle( 3719): com.google.android.gms.dynamite.DynamiteModule$LoadingException: No acceptable module found. Local version is 0 and remote version is 0.
E/BarcodeNativeHandle( 3719): 	at com.google.android.gms.dynamite.DynamiteModule.load(Unknown Source)
E/BarcodeNativeHandle( 3719): 	at com.google.android.gms.internal.vision.zzm.zzq(Unknown Source)
E/BarcodeNativeHandle( 3719): 	at com.google.android.gms.internal.vision.zzm.isOperational(Unknown Source)
E/BarcodeNativeHandle( 3719): 	at com.google.android.gms.vision.barcode.BarcodeDetector.isOperational(Unknown Source)
E/BarcodeNativeHandle( 3719): 	at com.amolg.flutterbarcodescanner.BarcodeCaptureActivity.createCameraSource(BarcodeCaptureActivity.java:201)
E/BarcodeNativeHandle( 3719): 	at com.amolg.flutterbarcodescanner.BarcodeCaptureActivity.onCreate(BarcodeCaptureActivity.java:129)
E/BarcodeNativeHandle( 3719): 	at android.app.Activity.performCreate(Activity.java:5990)
E/BarcodeNativeHandle( 3719): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
E/BarcodeNativeHandle( 3719): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
E/BarcodeNativeHandle( 3719): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
E/BarcodeNativeHandle( 3719): 	at android.app.ActivityThread.access$800(ActivityThread.java:151)
E/BarcodeNativeHandle( 3719): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
E/BarcodeNativeHandle( 3719): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/BarcodeNativeHandle( 3719): 	at android.os.Looper.loop(Looper.java:135)
E/BarcodeNativeHandle( 3719): 	at android.app.ActivityThread.main(ActivityThread.java:5254)
E/BarcodeNativeHandle( 3719): 	at java.lang.reflect.Method.invoke(Native Method)
E/BarcodeNativeHandle( 3719): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/BarcodeNativeHandle( 3719): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
E/BarcodeNativeHandle( 3719): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
W/GooglePlayServicesUtil( 3719): Google Play Store is missing.
E/GoogleApiAvailability( 3719): Google Play services is invalid. Cannot recover.
W/EGL_emulation( 3719): eglSurfaceAttrib not implemented
W/OpenGLRenderer( 3719): Failed to set EGL_SWAP_BEHAVIOR on surface 0xf3e983c0, error=EGL_SUCCESS
W/EGL_emulation( 3719): eglSurfaceAttrib not implemented
W/OpenGLRenderer( 3719): Failed to set EGL_SWAP_BEHAVIOR on surface 0xf3e98400, error=EGL_SUCCESS
I/Choreographer( 3719): Skipped 34 frames!  The application may be doing too much work on its main thread.
I/Choreographer( 3719): Skipped 79 frames!  The application may be doing too much work on its main thread.
```

**Comment by AmolGangadhare** [comment]
Thanks for using the plugin.
Unfortunately, you faced this issue. If you don't mind can you provide some details::
1. Steps to reproduce.
2. Is Play services available in the device (in case of Android).
3. Did you face this issue on only Android or in iPhone also?
4. Does this crash when you start barcode scanning?
5. If possible can you add some code you tried with and device info?

Thanks

**Comment by brun0xon** [comment]
> Thanks for using the plugin.
> Unfortunately, you faced this issue. If you don't mind can you provide some details::
> 
> 1. Steps to reproduce.
> 2. Is Play services available in the device (in case of Android).
> 3. Did you face this issue on only Android or in iPhone also?
> 4. Does this crash when you start barcode scanning?
> 5. If possible can you add some code you tried with and device info?
> 
> Thanks

1. After installing app I disable network and try to run scanning by tap on a button. After that there is no reaction on screen. If I will reboot my device and try to run scanning again then it will being worked for a while.
2. I tried to run on 2 android devices: emulator (which has no services) and my phony (has services)
3. I was unable to test it on iOS
4. This log was printed when I tried to run scanning, but application was not crashed. Just no reaction
5. 
`Future<String> scanBarcode() async {
    String barcode;
    try {
      barcode =
      await FlutterBarcodeScanner.scanBarcode('#FFFFFF', 'Отмена', false);
    } on PlatformException catch (e) {
      if (e.code == 'PERMISSION_NOT_GRANTED') {
        barcode = 'ACCESS_DENIED';
      } else {
        barcode = null;
      }
    } on FormatException {
      barcode = null;
    }
    return barcode;
  }`

**Comment by AmolGangadhare** [comment]
@brun0xon Thanks for the details. 

In Android, mobile vision API is used to scan the barcode. I did some research on this and found some answers that at the very first time play services need to download some additional files whenever the barcode engine is used for the first time (It is all internal process by GMS so no need to do anything externally). After that, everything is expected to work fine in online and offline mode. So I need some time to test this that is this really GMS related issue and also will try to find any way whether this thing can be detected earlier or can be eliminated.
Thanks

**Comment by AmolGangadhare** [comment]
@brun0xon 

Is the issue still there?

**Comment by brun0xon** [comment]
@AmolGangadhare 

Seems not to be

**Comment by AmolGangadhare** [comment]
Thanks for confirming. 

As the vision api is now deprecated, the new MLKit will be implemented for Android part. 

This might resolve any potential issue similar to this.

As the issue seems to be not there, should we close this ?

**Comment by brun0xon** [comment]
Yep
