### ISSUE TITLE
No implementation found for method scanBarcode on channel flutter_barcode_scanner

### ISSUE THREAD

**Issue by BLACKCAT25896** [AmolGangadhare/flutter_barcode_scanner#287]
Performing hot reload...
Syncing files to device RMX3231...
I/ActivityThread( 3867): smart_link is  not supported!!!
Reloaded 1 of 1641 libraries in 3,560ms.
D/IMGGralloc( 3867): Gralloc Register  w:720, h:1512, f:0x1, usage:0xb00, ui64Stamp:539727, sSize:4378624, line = 2335
D/IMGGralloc( 3867): Gralloc Register  w:720, h:1600, f:0x1, usage:0xb00, ui64Stamp:539729, sSize:4608000, line = 2335
D/IMGGralloc( 3867): Gralloc Register  w:720, h:1512, f:0x1, usage:0xb00, ui64Stamp:539735, sSize:4378624, line = 2335
E/flutter ( 3867): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: MissingPluginException(No implementation found for method scanBarcode on channel flutter_barcode_scanner)
E/flutter ( 3867): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:165:7)
E/flutter ( 3867): <asynchronous suspension>
E/flutter ( 3867): #1      FlutterBarcodeScanner.scanBarcode (package:flutter_barcode_scanner/flutter_barcode_scanner.dart:43:9)
E/flutter ( 3867): <asynchronous suspension>
E/flutter ( 3867): #2      _BarCodeScannerScreenState.build.<anonymous closure> (package:six_pos/view/screens/barcode_scanner/barcode_scanner_screen.dart:68:25)
E/flutter ( 3867): <asynchronous suspension>
E/flutter ( 3867):

**Comment by bernardoveras** [comment]
Hi, usually this error occurs when you install a dependency that makes some kind of connection with the android api.

Run the commands:

flutter clean
flutter pub get
