### ISSUE TITLE
Can this work in Flutter Desktop?

### ISSUE THREAD

**Issue by papakay** [AmolGangadhare/flutter_barcode_scanner#48]
I really commend the great work done in this package.

Please I like to confirm if this can work with Flutter Desktop embedding?

**Comment by AmolGangadhare** [comment]
Hi,

Thanks for using the plugin.
I've not checked whether the plugin is capable of working on the Flutter desktop / Flutter Web environment.

I will update you on this once I go through it.

**Comment by 926** [comment]
I checked,
Below the error :
I doubt adding the platform macos will then be enough to trigger embedded camera, but ready to pursue this further.



[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method scanBarcode on channel flutter_barcode_scanner)
#0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:319:7)
<asynchronous suspension>
#1      FlutterBarcodeScanner.scanBarcode (package:flutter_barcode_scanner/flutter_barcode_scanner.dart:42:43)

**Comment by BernardinD** [comment]
Any update on Desktop compatibility? Or even just Windows?
