### ISSUE TITLE
iOS build failure - pod install failure

### ISSUE THREAD

**Issue by jawand** [AmolGangadhare/flutter_barcode_scanner#6]
**Describe the bug**
created a blank application with `swift` and `java`. installed this package.

**To Reproduce**
1. `flutter run`

**Smartphone (please complete the following information):**
 - Device: iOS XR Simulator
 - Version Flutter 1.2.1

 **Logs**
 `Jawands-Mac:flutter_bar_code_scanner jawandsingh$ flutter run
Launching lib/main.dart on iPhone Xʀ in debug mode...
Running pod install...                                              1.2s
CocoaPods' output:
↳
      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)

    Fetching external sources
    -> Fetching podspec for `Flutter` from `.symlinks/flutter/ios`
    -> Fetching podspec for `flutter_barcode_scanner` from
    `.symlinks/plugins/flutter_barcode_scanner/ios`

    Resolving dependencies of `Podfile`
    [!] CocoaPods could not find compatible versions for pod "flutter_barcode_scanner":
      In Podfile:
        flutter_barcode_scanner (from `.symlinks/plugins/flutter_barcode_scanner/ios`)

    Specs satisfying the `flutter_barcode_scanner (from
    `.symlinks/plugins/flutter_barcode_scanner/ios`)` dependency were found, but they
    required a higher minimum deployment target.

    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.
    rb:328:in `raise_error_unless_state'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.
    rb:310:in `block in unwind_for_conflict'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.
    rb:308:in `tap'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.
    rb:308:in `unwind_for_conflict'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.
    rb:684:in `attempt_to_activate'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.
    rb:254:in `process_topmost_state'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.
    rb:182:in `resolve'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/molinillo-0.6.6/lib/molinillo/resolver.rb
    :43:in `resolve'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/resolver.rb
    :91:in `resolve'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/installer/a
    nalyzer.rb:909:in `block in resolve_dependencies'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/user_interf
    ace.rb:64:in `section'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/installer/a
    nalyzer.rb:907:in `resolve_dependencies'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/installer/a
    nalyzer.rb:114:in `analyze'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/installer.r
    b:266:in `analyze'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/installer.r
    b:174:in `block in resolve_dependencies'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/user_interf
    ace.rb:64:in `section'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/installer.r
    b:173:in `resolve_dependencies'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/installer.r
    b:136:in `install!'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/command/ins
    tall.rb:48:in `run'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/claide-1.0.2/lib/claide/command.rb:334:in
    `run'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/command.rb:
    52:in `run'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/bin/pod:55:in `<top
    (required)>'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/bin/pod:22:in `load'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/bin/pod:22:in `<main>'

Error output from CocoaPods:
↳
    [!] Automatically assigning platform `ios` with version `8.0` on target `Runner` because
    no platform was specified. Please specify a platform for this target in your Podfile.
    See https://guides.cocoapods.org/syntax/podfile.html#platform.
Error running pod install
Error launching application on iPhone Xʀ.`

**Flutter Doctor**
`Jawands-Mac:flutter_bar_code_scanner jawandsingh$ flutter doctor -v
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.4 18E226, locale en-GB)
    • Flutter version 1.2.1 at /Users/jawandsingh/Documents/development/flutter
    • Framework revision 8661d8aecd (8 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).
      If Android SDK has been installed to a custom location, set ANDROID_HOME to that location.
      You may also want to add it to your PATH environment variable.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2, Build version 10E125
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[✓] VS Code (version 1.33.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.25.0

[✓] Connected device (1 available)
    • iPhone Xʀ • B95B7422-090E-4B66-8DA9-3433121B259C • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)

! Doctor found issues in 2 categories.
`

**Comment by jawand** [comment]
sorry about it. Should have read the iOS documentation. I need to change the Deployment target to 10.
