### ISSUE TITLE
Android java.lang.NullPointerException

### ISSUE THREAD

**Issue by koteezy** [AmolGangadhare/flutter_barcode_scanner#68]
**Describe the bug**
Hello! We got this error from google play console. It's all information what we have.

**Smartphone**
 - Device: Oppo A5 2020 (OP4B79L1)
 - OS: Android 9

**Logs**
```
java.lang.RuntimeException: 
  at android.app.ActivityThread.deliverResults (ActivityThread.java:4707)
  at android.app.ActivityThread.handleSendResult (ActivityThread.java:4749)
  at android.app.servertransaction.ActivityResultItem.execute (ActivityResultItem.java:49)
  at android.app.servertransaction.TransactionExecutor.executeCallbacks (TransactionExecutor.java:114)
  at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:74)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1994)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:226)
  at android.app.ActivityThread.main (ActivityThread.java:7231)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:500)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:913)
Caused by: java.lang.NullPointerException: 	at com.amolg.flutterbarcodescanner.d.a(Unknown Source:28)
	at d.a.b.e.a(Unknown Source:18)
	at d.a.b.b.a(Unknown Source:6)
	at d.a.b.a.onActivityResult(Unknown Source:2)
	at android.app.Activity.dispatchActivityResult(Activity.java:7695)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:4700)
```

**Comment by AmolGangadhare** [comment]
Hello,

I was unable to reproduce this issue at my end.

V1.0.0 has been released, can you try it on the latest and confirm the same?

**Comment by koteezy** [comment]
Hello!

This log was from google play console, i don't remember what i had this issue on my local device :/

**Comment by AmolGangadhare** [comment]
@koteezy 
Possible fixes have been made, I was not able to reproduce this issue at my end.

Should I close this issue as of now?
Feel free to reopen if you face this in the future or create a new issue.

**Comment by vglider** [comment]
i have same or similar issue: here my console:

`D/Camera  (16790): app passed NULL surface
I/Camera  (16790): close camera: 0, package name: nickjdv.registrovisitatori
I/HwSystemManager(16790): pkgName = nickjdv.registrovisitatori pid = 16790uidOf3RdApk = 10118permType = 0permCfg=0
I/BackgroundPermManager(16790): pkgName: nickjdv.registrovisitatori,pid: 16790 ,uidOf3RdApk: 10118 ,permType: 0 ,permCfg: 0
D/AndroidRuntime(16790): Shutting down VM
E/AndroidRuntime(16790): FATAL EXCEPTION: main
E/AndroidRuntime(16790): Process: nickjdv.registrovisitatori, PID: 16790
E/AndroidRuntime(16790): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=9001, result=0, data=Intent { (has extras) }} to activity {nickjdv.registrovisitatori/nickjdv.registrovisitatori.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.MethodChannel$Result.success(java.lang.Object)' on a null object reference
E/AndroidRuntime(16790): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5041)
E/AndroidRuntime(16790): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5084)
E/AndroidRuntime(16790): 	at android.app.ActivityThread.-wrap20(Unknown Source:0)
E/AndroidRuntime(16790): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2053)
E/AndroidRuntime(16790): 	at android.os.Handler.dispatchMessage(Handler.java:108)
E/AndroidRuntime(16790): 	at android.os.Looper.loop(Looper.java:166)
E/AndroidRuntime(16790): 	at android.app.ActivityThread.main(ActivityThread.java:7529)
E/AndroidRuntime(16790): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(16790): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
E/AndroidRuntime(16790): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
E/AndroidRuntime(16790): Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.MethodChannel$Result.success(java.lang.Object)' on a null object reference
E/AndroidRuntime(16790): 	at com.amolg.flutterbarcodescanner.FlutterBarcodeScannerPlugin.onActivityResult(FlutterBarcodeScannerPlugin.java:157)
E/AndroidRuntime(16790): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEnginePluginRegistry.java:634)
E/AndroidRuntime(16790): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry.onActivityResult(FlutterEnginePluginRegistry.java:367)
E/AndroidRuntime(16790): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:546)
E/AndroidRuntime(16790): 	at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:594)
E/AndroidRuntime(16790): 	at android.app.Activity.dispatchActivityResult(Activity.java:7701)
E/AndroidRuntime(16790): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5037)
E/AndroidRuntime(16790): 	... 9 more
I/flutter (16790): 80007814
I/Process (16790): Sending signal. PID: 16790 SIG: 9
`

my app totally crush

**Comment by AmolGangadhare** [comment]
@koteezy 

Have you tried it with the new version?

**Comment by AmolGangadhare** [comment]
Is the issue persists with V 2.0.0? 


please acknowledge
