### ISSUE TITLE
App crash from two bugs when using barcode scanner 

### ISSUE THREAD

**Issue by talhazzani** [AmolGangadhare/flutter_barcode_scanner#81]
**Describe the bug**
when users use the barcode scanner I get many crashes through firebase crashlytics

1-two crashes where occurring 
  BarcodeCaptureActivity.java line 114

2-FlutterBarcodeScannerPlugin.java line 188
  com.amolg.flutterbarcodescanner.FlutterBarcodeScannerPlugin.onActivityResult

com.amolg.flutterbarcodescanner.BarcodeCaptureActivity.onCreate
**To Reproduce**
-use the barcode scanner 

**Smartphone (please complete the following information):**
 - OS: Android 
 - Version: all version 

**Additional context**
two crashes where reported below are the stack traces that were reported:

First:
///////////////////////////////////
BarcodeCaptureActivity.java line 114
com.amolg.flutterbarcodescanner.BarcodeCaptureActivity.onCreate

Fatal Exception: java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/core/widget/TintableCompoundDrawablesView;
       at androidx.appcompat.app.AppCompatDelegateImpl.createView(AppCompatDelegateImpl.java:1383)
       at androidx.appcompat.app.AppCompatDelegateImpl.onCreateView(AppCompatDelegateImpl.java:1457)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:811)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:769)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:531)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:461)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:383)
       at com.android.internal.policy.DecorView.onResourcesLoaded(DecorView.java:2704)
       at com.android.internal.policy.PhoneWindow.generateLayout(PhoneWindow.java:2734)
       at com.android.internal.policy.PhoneWindow.installDecor(PhoneWindow.java:2807)
       at com.android.internal.policy.PhoneWindow.getDecorView(PhoneWindow.java:2110)
       at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:717)
       at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:659)
       at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:552)
       at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:161)
       at com.amolg.flutterbarcodescanner.BarcodeCaptureActivity.onCreate(BarcodeCaptureActivity.java:114)
       at android.app.Activity.performCreate(Activity.java:7327)
       at android.app.Activity.performCreate(Activity.java:7318)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1275)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3095)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3258)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1955)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7073)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)

Caused by java.lang.ClassNotFoundException
Didn't find class "androidx.core.widget.TintableCompoundDrawablesView" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.channels.qwikleads-Uq1Gj_ju0clL-vusLKyR8g==/base.apk"],nativeLibraryDirectories=[/data/app/com.channels.qwikleads-Uq1Gj_ju0clL-vusLKyR8g==/lib/arm, /data/app/com.channels.qwikleads-Uq1Gj_ju0clL-vusLKyR8g==/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]

Caused by java.lang.ClassNotFoundException: Didn't find class "androidx.core.widget.TintableCompoundDrawablesView" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.channels.qwikleads-Uq1Gj_ju0clL-vusLKyR8g==/base.apk"],nativeLibraryDirectories=[/data/app/com.channels.qwikleads-Uq1Gj_ju0clL-vusLKyR8g==/lib/arm, /data/app/com.channels.qwikleads-Uq1Gj_ju0clL-vusLKyR8g==/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
       at androidx.appcompat.app.AppCompatDelegateImpl.createView(AppCompatDelegateImpl.java:1383)
       at androidx.appcompat.app.AppCompatDelegateImpl.onCreateView(AppCompatDelegateImpl.java:1457)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:811)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:769)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:531)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:461)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:383)
       at com.android.internal.policy.DecorView.onResourcesLoaded(DecorView.java:2704)
       at com.android.internal.policy.PhoneWindow.generateLayout(PhoneWindow.java:2734)
       at com.android.internal.policy.PhoneWindow.installDecor(PhoneWindow.java:2807)
       at com.android.internal.policy.PhoneWindow.getDecorView(PhoneWindow.java:2110)
       at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:717)
       at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:659)
       at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:552)
       at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:161)
       at com.amolg.flutterbarcodescanner.BarcodeCaptureActivity.onCreate(BarcodeCaptureActivity.java:114)
       at android.app.Activity.performCreate(Activity.java:7327)
       at android.app.Activity.performCreate(Activity.java:7318)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1275)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3095)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3258)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1955)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7073)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)

////////////////////

Second :

FlutterBarcodeScannerPlugin.java line 188
com.amolg.flutterbarcodescanner.FlutterBarcodeScannerPlugin.onActivityResult

Fatal Exception: java.lang.RuntimeException
Unable to resume activity {com.channels.qwikleads/com.channels.qwikleads.MainActivity}: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=9001, result=0, data=null} to activity {com.channels.qwikleads/com.channels.qwikleads.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void d.b.b.a.o$d.a(java.lang.Object)' on a null object reference

Caused by java.lang.RuntimeException
Failure delivering result ResultInfo{who=null, request=9001, result=0, data=null} to activity {com.channels.qwikleads/com.channels.qwikleads.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void d.b.b.a.o$d.a(java.lang.Object)' on a null object reference

Caused by java.lang.NullPointerException
Attempt to invoke interface method 'void d.b.b.a.o$d.a(java.lang.Object)' on a null object reference

com.amolg.flutterbarcodescanner.FlutterBarcodeScannerPlugin.onActivityResult (FlutterBarcodeScannerPlugin.java:188)
io.flutter.app.FlutterPluginRegistry.onActivityResult (FlutterPluginRegistry.java:204)
io.flutter.app.FlutterActivityDelegate.onActivityResult (FlutterActivityDelegate.java:131)
io.flutter.app.FlutterActivity.onActivityResult (FlutterActivity.java:142)
android.app.Activity.dispatchActivityResult (Activity.java:7762)
android.app.ActivityThread.deliverResults (ActivityThread.java:4605)
android.app.ActivityThread.performResumeActivity (ActivityThread.java:4004)
android.app.ActivityThread.handleResumeActivity (ActivityThread.java:4047)
android.app.servertransaction.ResumeActivityItem.execute (ResumeActivityItem.java:51)
android.app.servertransaction.TransactionExecutor.executeLifecycleState (TransactionExecutor.java:145)
android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:70)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:1955)
android.os.Handler.dispatchMessage (Handler.java:106)
android.os.Looper.loop (Looper.java:214)
android.app.ActivityThread.main (ActivityThread.java:7073)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:493)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:964)

**Comment by talhazzani** [comment]
@AmolGangadhare  Any thoughts?

**Comment by AmolGangadhare** [comment]
@talhazzani 

Thanks for reporting the issue.

There is V 1.0.0 release pending. This issue might get fixed with the new release as there is a major migration happened. Let's see if this issue still persists in the new release.

Thanks

**Comment by talhazzani** [comment]
@AmolGangadhare Thanks for your support and great work.

Do you have an estimate when this release will be published ?

**Comment by talhazzani** [comment]
@AmolGangadhare Any updates

**Comment by kw2019ltd** [comment]
anyupdate?

**Comment by ArpanKIIT2017** [comment]
This issue is making the plugin useless. Please suggest a temporary fix atleast.

**Comment by talhazzani** [comment]
@ArpanKIIT2017  yes I agree, but I think @AmolGangadhare stopped supporting , I will use another plugin for my next release

**Comment by AmolGangadhare** [comment]
V1.0.0 has been released, can you try it on the latest and confirm the same?

**Comment by AmolGangadhare** [comment]
This issue has been resolved in the latest release. 

Closing the issue as there is no response on this issue.
