### ISSUE TITLE
Error and crash on Success or on Cancel

### ISSUE THREAD

**Issue by EArminjon** [AmolGangadhare/flutter_barcode_scanner#88]
**Describe the bug**
App print lot of error (java) in console when scan start.
On success or on cancel, app crash.

**To Reproduce**
``dart
              RaisedButton(
                onPressed: () async {
                    String barcodeScanRes = await FlutterBarcodeScanner.scanBarcode("#ff1100", "Cancel", false, ScanMode.QR);
                },
                child: Text("scan"),
              ),
``
**Expected behavior**

**Screenshots**
```
W/art     ( 4969): Before Android 4.1, method android.graphics.PorterDuffColorFilter androidx.vectordrawable.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
I/art     ( 4969): Rejecting re-init on previously-failed class java.lang.Class<androidx.core.view.ViewCompat$2>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/view/View$OnUnhandledKeyEventListener;
I/art     ( 4969):   at void androidx.core.view.ViewCompat.setOnApplyWindowInsetsListener(android.view.View, androidx.core.view.OnApplyWindowInsetsListener) (ViewCompat.java:2436)
I/art     ( 4969):   at android.view.ViewGroup androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor() (AppCompatDelegateImpl.java:779)
I/art     ( 4969):   at void androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor() (AppCompatDelegateImpl.java:659)
I/art     ( 4969):   at void androidx.appcompat.app.AppCompatDelegateImpl.setContentView(int) (AppCompatDelegateImpl.java:552)
I/art     ( 4969):   at void androidx.appcompat.app.AppCompatActivity.setContentView(int) (AppCompatActivity.java:161)
I/art     ( 4969):   at void com.amolg.flutterbarcodescanner.BarcodeCaptureActivity.onCreate(android.os.Bundle) (BarcodeCaptureActivity.java:109)
I/art     ( 4969):   at void android.app.Activity.performCreate(android.os.Bundle) (Activity.java:6662)
I/art     ( 4969):   at void android.app.Instrumentation.callActivityOnCreate(android.app.Activity, android.os.Bundle) (Instrumentation.java:1118)
I/art     ( 4969):   at android.app.Activity android.app.ActivityThread.performLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:2599)
I/art     ( 4969):   at void android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:2707)
I/art     ( 4969):   at void android.app.ActivityThread.-wrap12(android.app.ActivityThread, android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:-1)
I/art     ( 4969):   at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1460)
I/art     ( 4969):   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:102)
I/art     ( 4969):   at void android.os.Looper.loop() (Looper.java:154)
I/art     ( 4969):   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6077)
I/art     ( 4969):   at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
I/art     ( 4969):   at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:866)
I/art     ( 4969):   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:756)
I/art     ( 4969): Caused by: java.lang.ClassNotFoundException: Didn't find class "android.view.View$OnUnhandledKeyEventListener" on path: DexPathList[[zip file "/data/app/net.beyondgravity.enterprises.enterprises-2/base.apk"],nativeLibraryDirectories=[/data/app/net.beyondgravity.enterprises.enterprises-2/lib/x86, /data/app/net.beyondgravity.enterprises.enterprises-2/base.apk!/lib/x86, /system/lib, /vendor/lib]]
I/art     ( 4969):   at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:56)
I/art     ( 4969):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:380)
I/art     ( 4969):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
I/art     ( 4969):   at void androidx.core.view.ViewCompat.setOnApplyWindowInsetsListener(android.view.View, androidx.core.view.OnApplyWindowInsetsListener) (ViewCompat.java:2436)
I/art     ( 4969):   at android.view.ViewGroup androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor() (AppCompatDelegateImpl.java:779)
I/art     ( 4969):   at void androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor() (AppCompatDelegateImpl.java:659)
I/art     ( 4969):   at void androidx.appcompat.app.AppCompatDelegateImpl.setContentView(int) (AppCompatDelegateImpl.java:552)
I/art     ( 4969):   at void androidx.appcompat.app.AppCompatActivity.setContentView(int) (AppCompatActivity.java:161)
I/art     ( 4969):   at void com.amolg.flutterbarcodescanner.BarcodeCaptureActivity.onCreate(android.os.Bundle) (BarcodeCaptureActivity.java:109)
I/art     ( 4969):   at void android.app.Activity.performCreate(android.os.Bundle) (Activity.java:6662)
I/art     ( 4969):   at void android.app.Instrumentation.callActivityOnCreate(android.app.Activity, android.os.Bundle) (Instrumentation.java:1118)
I/art     ( 4969):   at android.app.Activity android.app.ActivityThread.performLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:2599)
I/art     ( 4969):   at void android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:2707)
I/art     ( 4969):   at void android.app.ActivityThread.-wrap12(android.app.ActivityThread, android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:-1)
I/art     ( 4969):   at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1460)
I/art     ( 4969):   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:102)
I/art     ( 4969):   at void android.os.Looper.loop() (Looper.java:154)
I/art     ( 4969):   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6077)
I/art     ( 4969):   at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
I/art     ( 4969):   at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:866)
I/art     ( 4969):   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:756)
I/art     ( 4969): 
W/DynamiteModule( 4969): Local module descriptor class for com.google.android.gms.vision.dynamite.barcode not found.
I/DynamiteModule( 4969): Considering local module com.google.android.gms.vision.dynamite.barcode:0 and remote module com.google.android.gms.vision.dynamite.barcode:0
D/BarcodeNativeHandle( 4969): Cannot load feature, fall back to load dynamite module.
W/DynamiteModule( 4969): Local module descriptor class for com.google.android.gms.vision.dynamite not found.
I/DynamiteModule( 4969): Considering local module com.google.android.gms.vision.dynamite:0 and remote module com.google.android.gms.vision.dynamite:2501
I/DynamiteModule( 4969): Selected remote version of com.google.android.gms.vision.dynamite, version >= 2501
V/DynamiteModule( 4969): Dynamite loader version >= 2, using loadModule2NoCrashUtils
W/System  ( 4969): ClassLoader referenced unknown path: 
W/System  ( 4969): ClassLoader referenced unknown path: /system/priv-app/PrebuiltGmsCore/lib/x86
W/System  ( 4969): ClassLoader referenced unknown path: /data/user_de/0/com.google.android.gms/app_chimera/m/00000003/n/x86
W/System  ( 4969): ClassLoader referenced unknown path: /system/priv-app/PrebuiltGmsCore/lib/x86
I/Vision  ( 4969): Loading library libbarhopper.so
W/linker  ( 4969): /data/data/com.google.android.gms/app_vision/barcode/libs/x86/libbarhopper.so: unused DT entry: type 0x7ffffffd arg 0x73c
I/Vision  ( 4969): libbarhopper.so library load status: true
I/DynamiteModule( 4969): Considering local module com.google.android.gms.flags:3 and remote module com.google.android.gms.flags:3
I/DynamiteModule( 4969): Selected local version of com.google.android.gms.flags
D/EGL_emulation( 4969): eglMakeCurrent: 0x947bc2a0: ver 2 0 (tinfo 0x947d25c0)
D/Camera  ( 4969): app passed NULL surface
D/AndroidRuntime( 4969): Shutting down VM
E/AndroidRuntime( 4969): FATAL EXCEPTION: main
E/AndroidRuntime( 4969): Process: net.beyondgravity.enterprises.enterprises, PID: 4969
E/AndroidRuntime( 4969): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=9001, result=0, data=Intent { (has extras) }} to activity {net.beyondgravity.enterprises.enterprises/net.beyondgravity.enterprises.enterprises.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.MethodChannel$Result.success(java.lang.Object)' on a null object reference
E/AndroidRuntime( 4969): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4053)
E/AndroidRuntime( 4969): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4096)
E/AndroidRuntime( 4969): 	at android.app.ActivityThread.-wrap20(ActivityThread.java)
E/AndroidRuntime( 4969): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1516)
E/AndroidRuntime( 4969): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 4969): 	at android.os.Looper.loop(Looper.java:154)
E/AndroidRuntime( 4969): 	at android.app.ActivityThread.main(ActivityThread.java:6077)
E/AndroidRuntime( 4969): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 4969): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
E/AndroidRuntime( 4969): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
E/AndroidRuntime( 4969): Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.MethodChannel$Result.success(java.lang.Object)' on a null object reference
E/AndroidRuntime( 4969): 	at com.amolg.flutterbarcodescanner.FlutterBarcodeScannerPlugin.onActivityResult(FlutterBarcodeScannerPlugin.java:157)
E/AndroidRuntime( 4969): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEnginePluginRegistry.java:634)
E/AndroidRuntime( 4969): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry.onActivityResult(FlutterEnginePluginRegistry.java:367)
E/AndroidRuntime( 4969): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:546)
E/AndroidRuntime( 4969): 	at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:594)
E/AndroidRuntime( 4969): 	at android.app.Activity.dispatchActivityResult(Activity.java:6915)
E/AndroidRuntime( 4969): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4049)
E/AndroidRuntime( 4969): 	... 9 more
``

**Smartphone **
- Android emulator, custom (tablet) like : 800x1280 mdpi API 24 Android 7.0 x86
- Flutter channel stable : v1.12.13+hotfix.9
- flutter_barcode_scanner: ^1.0.0

**Comment by Anzell** [comment]
Yes, same with me. But the Stream works fine =S

**Comment by psycura** [comment]
I have issue with Stream on ios:

> Fatal error: Unexpectedly found nil while unwrapping an Optional value: file 

> /Users/eugenealitz/.pub-cache/git/flutter_barcode_scanner-cbc5b51f8503bc8fe78119bab5d6c6215f41e8cb/ios/Classes/SwiftFlutterBarcodeScannerPlugin.swift, line 55
> 2020-05-05 12:21:37.115513+0300 Runner[707:208642] Fatal error: Unexpectedly found nil while unwrapping an Optional value: file /Users/eugenealitz/.pub-cache/git/flutter_barcode_scanner-cbc5b51f8503bc8fe78119bab5d6c6215f41e8cb/ios/Classes/SwiftFlutterBarcodeScannerPlugin.swift, line 55

**Comment by AmolGangadhare** [comment]
Please check with the latest V 2.0.0
