### ISSUE TITLE
CRASH java.lang.NullPointerException: Attempt to invoke interface method 'void 

### ISSUE THREAD

**Issue by Xgamefactory** [AmolGangadhare/flutter_barcode_scanner#91]
```
java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.EventChannel$EventSink.success(java.lang.Object)' on a null object reference
E/AndroidRuntime(32669): 	at com.amolg.flutterbarcodescanner.FlutterBarcodeScannerPlugin$1.run(FlutterBarcodeScannerPlugin.java:201)
E/AndroidRuntime(32669): 	at android.os.Handler.handleCallback(Handler.java:883)
E/AndroidRuntime(32669): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/AndroidRuntime(32669): 	at android.os.Looper.loop(Looper.java:237)
E/AndroidRuntime(32669): 	at android.app.ActivityThread.main(ActivityThread.java:7857)
E/AndroidRuntime(32669): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(32669): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/AndroidRuntime(32669): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)
I/Process (32669): Sending signal. PID: 32669 SIG: 9
Lost connection to device.
```

what i try to do is stream barcodes and get only qrcode not standar ean carcodes. 

String res = await FlutterBarcodeScanner.getBarcodeStreamReceiver(
            "#ff6666", "Cancel", true, ScanMode.QR)
        .firstWhere((code) {
      print("singleWhere $code");
      if (code.toString().startsWith("http")) {
        print("founded");
        return true;
      }
      return false;
    });

**Comment by prokons** [comment]
I have same problem with example code:

> Attempt to invoke interface method 'void io.flutter.plugin.common.MethodChannel$Result.success(java.lang.Object)' on a null object reference

Actually qrcode value is read into barcodeScanRes but then app crashes

```
Future<void> scanQR() async {
    String barcodeScanRes;
    // Platform messages may fail, so we use a try/catch PlatformException.
    try {
      barcodeScanRes = await FlutterBarcodeScanner.scanBarcode("#ff6666", "Cancel", true, ScanMode.QR);
      print(barcodeScanRes);
    } on PlatformException {
      barcodeScanRes = 'Failed to get platform version.';
    }
    if (!mounted) return;

    setState(() {
      _scanBarcode = barcodeScanRes;
    });
```

Android studio 3.6.3
Runtime version 1.8.0_212
Flutter version 1.12.13+hotfix.9
Emulator Pixel2, API 23

**Comment by Xgamefactory** [comment]
yes latest plugin causes crash.

**Comment by prokons** [comment]
Unfortunately also barcode_scan is not working for me
https://github.com/mintware-de/flutter_barcode_reader/issues/226#issuecomment-623088525

**Comment by AmolGangadhare** [comment]
@Xgamefactory 

Can you provide a sample barcode so I can reproduce this issue?

**Comment by prokons** [comment]
At last I managed to make barcode_scan running and I used it. 
Anyway. as a sample, I just used an online generated qrCode with my name.

**Comment by vglider** [comment]
i have same problem and it happened using your example as test.
the only way to not making crash the app is the streaming barcode , it gets the code but i have to navigate back to my page....there is another way to make it work?

**Comment by vglider** [comment]
i tried to recreate  by my self `getBarcodeStreamReceiver ` closing at the first code got.
when:
`"isContinuousScan": true,`

evreything is ok, when i try to change it in : 
`"isContinuousScan": true,`

it crashes

**Comment by vglider** [comment]
i've just tried using .single or .first instead of .listen but it doesn't quit cam. i need to close at first element. and any way i try it doesn't work. i need it soon as possible

**Comment by AmolGangadhare** [comment]
@vglider Allow me some time to reproduce this issue at my end.

Meanwhile, can you provide me some details like which device on which you are facing the issue?

**Comment by vglider** [comment]
> @vglider Allow me some time to reproduce this issue at my end.
> 
> Meanwhile, can you provide me some details like which device on which you are facing the issue?

i'm using huaweu mediapad t5

**Comment by vglider** [comment]
i build my widget with GestureDetector, wich my onTap function is:

`function: () {
                    scanner.FlutterBarcodeScanner.getBarcodeStreamReceiver(
                      "#000000",
                      "Cancel",
                      false,
                      scanner.ScanMode.DEFAULT,
                    ).listen(
                      (code) {
                        userQR = code;
                        print(userQR);
                      },
                    );
                  },`

**Comment by vglider** [comment]
i tried with another device but stil the same... i used Alcatel 1S (Android 9.0)

**Comment by vglider** [comment]
@AmolGangadhare have you replicated the issue?

**Comment by rymesaint** [comment]
i got this issue too

**Comment by vglider** [comment]
@AmolGangadhare hi, i just upgrade my flutter version (now is: 1.17.3) and normal scan works...thanks

**Comment by AmolGangadhare** [comment]
Please check with v 2.0.0 if the issue still there. Potential fix has been made.
